//! API routes
//!
//! # Route handler pattern
//!
//! All route handlers follow a consistent pattern:
//!
//! 1. **Decode request** — use `try_decode!` / `crypto_validation::decode_*`
//!    to parse and validate base64url fields from the request body or path.
//! 2. **Build handler & command** — instantiate the application-layer handler
//!    with repos from the sub-state, and construct the command/query struct.
//! 3. **Execute & map result** — `match handler.handle(cmd).await` and map
//!    `Ok` to the appropriate response, `Err` via `app_error_response!`.
//!
//! The `app_error_response!` macro translates `AppError` classification
//! methods (`is_not_found`, `is_access_denied`, etc.) to HTTP status codes.
//! Each error response type is generated by `error_response_struct!`.

pub mod auth;
pub mod device;
pub mod document;
pub mod encryption;
pub mod invitation;
pub mod trust_transfer;
pub mod workspace;

use crate::AppState;
use crate::auth::PopLayer;
use axum::Router;

/// Generate an error response struct with `error: String` field.
///
/// Optionally accepts a schema example string for OpenAPI docs.
macro_rules! error_response_struct {
    ($name:ident) => {
        #[derive(Debug, serde::Serialize, utoipa::ToSchema)]
        pub struct $name {
            pub error: String,
        }
    };
    ($name:ident, $example:literal) => {
        #[derive(Debug, serde::Serialize, utoipa::ToSchema)]
        pub struct $name {
            #[schema(example = $example)]
            pub error: String,
        }
    };
}
pub(crate) use error_response_struct;

/// Map an application error to an HTTP error response.
///
/// Usage:
/// - `app_error_response!(e, ResponseType, [checks...])` — standard mapping
/// - `app_error_response!(e, ResponseType)` — ISE-only (no classification checks)
/// - `app_error_response!(e, ResponseType, @safe, [checks...])` — uses `safe_message()`
///   instead of `to_string()` to prevent information leakage (e.g., user enumeration)
///
/// Checks are any combination of: `bad_request` (is_invalid_input), `not_found`,
/// `forbidden` (is_access_denied), `conflict`, `unauthorized` (is_unauthenticated),
/// `gone`. The ISE fallback is always included.
macro_rules! app_error_response {
    // ISE-only: no classification checks, always returns 500
    ($e:expr, $resp_type:ident) => {{
        let e = $e;
        tracing::error!("internal error: {}", e);
        (
            axum::http::StatusCode::INTERNAL_SERVER_ERROR,
            axum::Json($resp_type { error: "internal server error".to_string() }),
        ).into_response()
    }};
    // Safe-message variant: uses SafeMessage trait to prevent information leakage
    ($e:expr, $resp_type:ident, @safe, $($check:ident),+ $(,)?) => {{
        let e = $e;
        let (status, _) = app_error_response!(@match e, $($check),+);
        (status, axum::Json($resp_type { error: application::types::SafeMessage::safe_message(&e).to_string() })).into_response()
    }};
    // Standard variant with classification checks
    ($e:expr, $resp_type:ident, $($check:ident),+ $(,)?) => {{
        let e = $e;
        let (status, message) = app_error_response!(@match e, $($check),+);
        (status, axum::Json($resp_type { error: message })).into_response()
    }};
    // Internal: build the if-else chain from check list
    (@match $e:ident, $head:ident $(, $tail:ident)*) => {
        if app_error_response!(@check $e, $head) {
            (app_error_response!(@status $head), $e.to_string())
        } else {
            app_error_response!(@match $e $(, $tail)*)
        }
    };
    // Terminal case: ISE fallback
    (@match $e:ident) => {{
        tracing::error!("internal error: {}", $e);
        (
            axum::http::StatusCode::INTERNAL_SERVER_ERROR,
            "internal server error".to_string(),
        )
    }};
    // Map check name to method call (fully qualified to avoid requiring trait import at call site)
    (@check $e:ident, bad_request) => { application::types::AppError::is_invalid_input(&$e) };
    (@check $e:ident, not_found) => { application::types::AppError::is_not_found(&$e) };
    (@check $e:ident, forbidden) => { application::types::AppError::is_access_denied(&$e) };
    (@check $e:ident, conflict) => { application::types::AppError::is_conflict(&$e) };
    (@check $e:ident, unauthorized) => { application::types::AppError::is_unauthenticated(&$e) };
    (@check $e:ident, gone) => { application::types::AppError::is_gone(&$e) };
    (@check $e:ident, unprocessable) => { application::types::AppError::is_unprocessable(&$e) };
    // Map check name to status code
    (@status bad_request) => { axum::http::StatusCode::BAD_REQUEST };
    (@status not_found) => { axum::http::StatusCode::NOT_FOUND };
    (@status forbidden) => { axum::http::StatusCode::FORBIDDEN };
    (@status conflict) => { axum::http::StatusCode::CONFLICT };
    (@status unauthorized) => { axum::http::StatusCode::UNAUTHORIZED };
    (@status gone) => { axum::http::StatusCode::GONE };
    (@status unprocessable) => { axum::http::StatusCode::UNPROCESSABLE_ENTITY };
}

pub(crate) use app_error_response;

/// Create all API routes
pub fn create_routes(state: AppState) -> Result<Router, anyhow::Error> {
    Ok(Router::new().nest("/api", api_routes(state)?))
}

fn api_routes(state: AppState) -> Result<Router, anyhow::Error> {
    let pop_layer = PopLayer::new(
        state.device_repo(),
        state.session_repo(),
        state.challenge_store(),
    );

    // Routes requiring PoP verification (session auth + PoP checked by middleware)
    //
    // Merge all workspace-scoped routers into a single router before nesting
    // under "/workspaces". Multiple `.nest()` calls with the same prefix can
    // cause the first nested scope to 404 without falling through to the others.
    let workspace_pop_routes = workspace::pop_routes(state.clone())
        .merge(workspace::invitation_routes(state.clone()))
        .merge(document::workspace_document_routes(state.clone()));

    let pop_protected = Router::new()
        .nest("/workspaces", workspace_pop_routes)
        .nest("/invitations", invitation::pop_routes(state.clone()))
        .nest("/documents", document::routes(state.clone()))
        .nest("/encryption", encryption::routes(state.clone()))
        .nest("/devices", device::pop_routes(state.clone()))
        .nest("/trust-transfer", trust_transfer::pop_routes(state.clone()))
        .layer(pop_layer);

    // Routes requiring session auth only (no PoP)
    let session_only = Router::new()
        .nest("/auth", auth::routes(state.clone())?)
        .nest("/devices", device::session_routes(state.clone())?)
        .nest("/workspaces", workspace::session_routes(state.clone()))
        .nest("/trust-transfer", trust_transfer::session_routes(state));

    Ok(Router::new()
        .merge(pop_protected)
        .merge(session_only))
}
