//! API routes
//!
//! # Route handler pattern
//!
//! All route handlers follow a consistent pattern:
//!
//! 1. **Decode request** — use `try_decode!` / `crypto_validation::decode_*`
//!    to parse and validate base64url fields from the request body or path.
//! 2. **Build handler & command** — instantiate the application-layer handler
//!    with repos from the sub-state, and construct the command/query struct.
//! 3. **Execute & map result** — `match handler.handle(cmd).await` and map
//!    `Ok` to the appropriate response, `Err` via `app_error_response!`.
//!
//! The `app_error_response!` macro translates `AppError` classification
//! methods (`is_not_found`, `is_access_denied`, etc.) to HTTP status codes.
//! Each error response type is generated by `error_response_struct!`.

pub mod auth;
pub mod device;
pub mod document;
pub mod encryption;
pub mod invitation;
pub mod trust_transfer;
pub mod workspace;

use axum::extract::FromRef;
use axum::Router;
use axum::routing::get;

use crate::AppState;
use crate::auth::PopLayer;
use crate::ws;

/// Generate an error response struct with `error: String` field.
///
/// Optionally accepts a schema example string for OpenAPI docs.
macro_rules! error_response_struct {
    ($name:ident) => {
        #[derive(Debug, serde::Serialize, utoipa::ToSchema)]
        pub struct $name {
            pub error: String,
        }
    };
    ($name:ident, $example:literal) => {
        #[derive(Debug, serde::Serialize, utoipa::ToSchema)]
        pub struct $name {
            #[schema(example = $example)]
            pub error: String,
        }
    };
}
pub(crate) use error_response_struct;

/// Map an application error to an HTTP error response.
///
/// Usage:
/// - `app_error_response!(e, ResponseType, [checks...])` — standard mapping
/// - `app_error_response!(e, ResponseType)` — ISE-only (no classification checks)
/// - `app_error_response!(e, ResponseType, @safe, [checks...])` — uses `safe_message()`
///   instead of `to_string()` to prevent information leakage (e.g., user enumeration)
///
/// Checks are any combination of: `bad_request` (is_invalid_input), `not_found`,
/// `forbidden` (is_access_denied), `conflict`, `unauthorized` (is_unauthenticated),
/// `gone`. The ISE fallback is always included.
macro_rules! app_error_response {
    // ISE-only: no classification checks, always returns 500
    ($e:expr, $resp_type:ident) => {{
        let e = $e;
        tracing::error!("internal error: {}", e);
        (
            axum::http::StatusCode::INTERNAL_SERVER_ERROR,
            axum::Json($resp_type { error: "internal server error".to_string() }),
        ).into_response()
    }};
    // Safe-message variant: uses SafeMessage trait to prevent information leakage
    ($e:expr, $resp_type:ident, @safe, $($check:ident),+ $(,)?) => {{
        let e = $e;
        let (status, _) = app_error_response!(@match e, $($check),+);
        (status, axum::Json($resp_type { error: application::types::SafeMessage::safe_message(&e).to_string() })).into_response()
    }};
    // Standard variant with classification checks
    ($e:expr, $resp_type:ident, $($check:ident),+ $(,)?) => {{
        let e = $e;
        let (status, message) = app_error_response!(@match e, $($check),+);
        (status, axum::Json($resp_type { error: message })).into_response()
    }};
    // Internal: build the if-else chain from check list
    (@match $e:ident, $head:ident $(, $tail:ident)*) => {
        if app_error_response!(@check $e, $head) {
            (app_error_response!(@status $head), $e.to_string())
        } else {
            app_error_response!(@match $e $(, $tail)*)
        }
    };
    // Terminal case: ISE fallback
    (@match $e:ident) => {{
        tracing::error!("internal error: {}", $e);
        (
            axum::http::StatusCode::INTERNAL_SERVER_ERROR,
            "internal server error".to_string(),
        )
    }};
    // Map check name to method call (fully qualified to avoid requiring trait import at call site)
    (@check $e:ident, bad_request) => { application::types::AppError::is_invalid_input(&$e) };
    (@check $e:ident, not_found) => { application::types::AppError::is_not_found(&$e) };
    (@check $e:ident, forbidden) => { application::types::AppError::is_access_denied(&$e) };
    (@check $e:ident, conflict) => { application::types::AppError::is_conflict(&$e) };
    (@check $e:ident, unauthorized) => { application::types::AppError::is_unauthenticated(&$e) };
    (@check $e:ident, gone) => { application::types::AppError::is_gone(&$e) };
    (@check $e:ident, unprocessable) => { application::types::AppError::is_unprocessable(&$e) };
    // Map check name to status code
    (@status bad_request) => { axum::http::StatusCode::BAD_REQUEST };
    (@status not_found) => { axum::http::StatusCode::NOT_FOUND };
    (@status forbidden) => { axum::http::StatusCode::FORBIDDEN };
    (@status conflict) => { axum::http::StatusCode::CONFLICT };
    (@status unauthorized) => { axum::http::StatusCode::UNAUTHORIZED };
    (@status gone) => { axum::http::StatusCode::GONE };
    (@status unprocessable) => { axum::http::StatusCode::UNPROCESSABLE_ENTITY };
}

pub(crate) use app_error_response;

/// Convert a typed `DocumentRelayEventPayload` to a presentation-layer `WsOutMessage`.
fn relay_event_payload_to_ws_out(
    payload: application::document_relay::DocumentRelayEventPayload,
) -> ws::messages::WsOutMessage {
    match payload {
        application::document_relay::DocumentRelayEventPayload::Document(relay) => match relay {
            application::document_relay::RelayPayload::Update(p) => {
                ws::messages::WsOutMessage::Update(ws::messages::WsUpdateEnvelope {
                    ciphertext: p.ciphertext,
                    nonce: p.nonce,
                    signature: p.signature,
                    public_data: p.public_data,
                    version: p.version,
                })
            }
            application::document_relay::RelayPayload::Snapshot(p) => {
                ws::messages::WsOutMessage::Snapshot {
                    snapshot_id: p.snapshot_id,
                    snapshot: ws::messages::WsSnapshotEnvelope {
                        ciphertext: p.ciphertext,
                        nonce: p.nonce,
                        signature: p.signature,
                        public_data: p.public_data,
                    },
                }
            }
        },
        application::document_relay::DocumentRelayEventPayload::Ephemeral(ephemeral) => {
            ws::messages::WsOutMessage::EphemeralMessage(ws::messages::WsEphemeralEnvelope {
                ciphertext: ephemeral.ciphertext,
                nonce: ephemeral.nonce,
                signature: ephemeral.signature,
                public_data: ephemeral.public_data,
            })
        }
    }
}

/// Create all API routes.
pub fn create_routes(
    state: AppState,
    connection_store: ws::DocumentConnectionStore,
    allowed_origins: Vec<String>,
) -> Result<Router, anyhow::Error> {
    let router = api_routes(state, connection_store, allowed_origins)?;
    Ok(Router::new().nest("/api", router))
}

/// Spawn background tasks that bridge event buses to WebSocket connections.
///
/// Called once per process from the composition root, separately from route creation
/// (design: websocket-scaling.md, Bootstrap section).
pub fn spawn_background_listeners(state: &AppState, connection_store: &ws::DocumentConnectionStore) {
    // Workspace events → WS disconnect (member removal / role change)
    {
        let connection_store = connection_store.clone();
        let doc_sub: crate::DocumentSubState = FromRef::from_ref(state);
        let service = application::workspace::WorkspaceDisconnectService::new(
            doc_sub.document_repo.clone(),
        );
        let workspace_sub: crate::WorkspaceSubState = FromRef::from_ref(state);
        let mut rx = application::workspace_events::WorkspaceEventSubscriber::subscribe(
            workspace_sub.workspace_event_bus.as_ref(),
        );
        tokio::spawn(async move {
            loop {
                match rx.recv().await {
                    Ok(event) => {
                        service.handle_event(&event, &connection_store).await;
                    }
                    Err(tokio::sync::broadcast::error::RecvError::Lagged(n)) => {
                        tracing::warn!("WS disconnect listener lagged by {n} events");
                    }
                    Err(tokio::sync::broadcast::error::RecvError::Closed) => break,
                }
            }
        });
    }

    // Document relay events → broadcast to local rooms
    {
        let connection_store = connection_store.clone();
        let doc_sub: crate::DocumentSubState = FromRef::from_ref(state);
        let relay_bus = state.document_relay_bus();
        let mut rx = application::document_relay::DocumentRelaySubscriber::subscribe(
            relay_bus.as_ref(),
        );
        tokio::spawn(async move {
            loop {
                match rx.recv().await {
                    Ok(event) => {
                        let msg = relay_event_payload_to_ws_out(event.payload);
                        if let Some(room) = connection_store.get_room(event.document_id) {
                            // Lazy RBAC check before broadcast (same as local path)
                            let rbac_ok = ws::handler::check_and_evict_unauthorized(
                                &doc_sub, &room, event.document_id,
                            ).await;
                            if rbac_ok {
                                room.broadcast_all(msg);
                            }
                        }
                    }
                    Err(tokio::sync::broadcast::error::RecvError::Lagged(n)) => {
                        tracing::warn!(
                            "Document relay listener lagged by {n} events, triggering resync for affected clients"
                        );
                        connection_store.disconnect_all_for_resync();
                    }
                    Err(tokio::sync::broadcast::error::RecvError::Closed) => break,
                }
            }
        });
    }

    // Redis reconnect → force disconnect all WS connections.
    // After Redis recovers from an outage, connected clients may have missed cross-node
    // updates. Force-closing triggers client delta reconnect from PostgreSQL
    // (design: websocket-scaling.md §Redis接続断, point 3).
    {
        let connection_store = connection_store.clone();
        let relay_bus = state.document_relay_bus();
        let mut reconnect_rx = application::document_relay::DocumentRelaySubscriber::subscribe_reconnect(
            relay_bus.as_ref(),
        );
        tokio::spawn(async move {
            loop {
                match reconnect_rx.recv().await {
                    Ok(()) => {
                        tracing::info!(
                            "Redis reconnected after outage, force-disconnecting all WS connections for PostgreSQL resync"
                        );
                        connection_store.disconnect_all_for_resync();
                    }
                    Err(tokio::sync::broadcast::error::RecvError::Lagged(n)) => {
                        tracing::warn!("Redis reconnect listener lagged by {n} events, triggering resync");
                        connection_store.disconnect_all_for_resync();
                    }
                    Err(tokio::sync::broadcast::error::RecvError::Closed) => break,
                }
            }
        });
    }
}

fn api_routes(
    state: AppState,
    connection_store: ws::DocumentConnectionStore,
    allowed_origins: Vec<String>,
) -> Result<Router, anyhow::Error> {
    let pop_layer = PopLayer::new(
        state.device_repo(),
        state.session_repo(),
        state.challenge_store(),
    );

    // Routes requiring PoP verification (session auth + PoP checked by middleware)
    //
    // Merge all workspace-scoped routers into a single router before nesting
    // under "/workspaces". Multiple `.nest()` calls with the same prefix can
    // cause the first nested scope to 404 without falling through to the others.
    let workspace_pop_routes = workspace::pop_routes(state.clone())
        .merge(workspace::invitation_routes(state.clone()))
        .merge(document::workspace_document_routes(state.clone()))
        .nest("/invitations", invitation::pop_routes(state.clone()));

    let pop_protected = Router::new()
        .nest("/workspaces", workspace_pop_routes)
        .nest("/documents", document::routes(state.clone()))
        .nest("/encryption", encryption::routes(state.clone()))
        .nest("/devices", device::pop_routes(state.clone()))
        .nest("/trust-transfer", trust_transfer::pop_routes(state.clone()))
        .layer(pop_layer);

    // WebSocket routes (session auth only, no PoP)
    let ws_state = ws::handler::WsState {
        document_sub_state: crate::DocumentSubState::from_ref(&state),
        session_repo: state.session_repo(),
        connection_store,
        allowed_origins,
    };

    let ws_routes = Router::new()
        .route(
            "/documents/{document_id}/ws",
            get(ws::handler::ws_document),
        )
        .with_state(ws_state);

    // Routes requiring session auth only (no PoP)
    let session_only = Router::new()
        .nest("/auth", auth::routes(state.clone())?)
        .nest("/devices", device::session_routes(state.clone())?)
        .nest("/workspaces", workspace::session_routes(state.clone()))
        .nest("/trust-transfer", trust_transfer::session_routes(state));

    Ok(Router::new()
        .merge(pop_protected)
        .merge(session_only)
        .merge(ws_routes))
}
