// This file is auto-generated by @hey-api/openapi-ts

export type ActiveShareItem = {
    created_at: string;
    document_id: string;
    document_title: string;
    /**
     * 'document' or 'folder'
     */
    document_type: string;
    expires_at?: (string) | null;
    id: string;
    parent_share_id?: (string) | null;
    permission: string;
    token: string;
    url: string;
};

export type AddPatternsRequest = {
    patterns: Array<string>;
};

export type ApiTokenCreateRequest = {
    name?: (string) | null;
};

export type ApiTokenCreateResponse = {
    created_at: string;
    id: string;
    name: string;
    token: string;
};

export type ApiTokenItem = {
    created_at: string;
    id: string;
    last_used_at?: (string) | null;
    name: string;
    revoked_at?: (string) | null;
};

export type ApplicableShareItem = {
    excluded: boolean;
    permission: string;
    /**
     * 'document' or 'folder'
     */
    scope: string;
    token: string;
};

export type BacklinkInfo = {
    document_id: string;
    document_type: string;
    file_path?: (string) | null;
    link_count: number;
    link_text?: (string) | null;
    link_type: string;
    title: string;
};

export type BacklinksResponse = {
    backlinks: Array<BacklinkInfo>;
    total_count: number;
};

export type CheckIgnoredRequest = {
    path: string;
};

export type CreateDocumentRequest = {
    parent_id?: (string) | null;
    title?: (string) | null;
    type?: (string) | null;
};

export type CreateGitConfigRequest = {
    auth_data: unknown;
    auth_type: string;
    auto_sync?: (boolean) | null;
    branch_name?: (string) | null;
    repository_url: string;
};

export type CreateRecordBody = {
    data: unknown;
};

export type CreateShareRequest = {
    document_id: string;
    expires_at?: (string) | null;
    permission?: (string) | null;
};

export type CreateShareResponse = {
    token: string;
    url: string;
};

export type Document = {
    archived_at?: (string) | null;
    archived_by?: (string) | null;
    archived_parent_id?: (string) | null;
    created_at: string;
    desired_path: string;
    id: string;
    owner_id: string;
    parent_id?: (string) | null;
    path?: (string) | null;
    slug: string;
    title: string;
    type: string;
    updated_at: string;
};

export type DocumentArchiveBinary = Blob | File;

export type DocumentDownloadBinary = Blob | File;

export type DocumentListResponse = {
    items: Array<Document>;
};

export type DownloadDocumentQuery = {
    format?: DownloadFormat;
    token?: (string) | null;
};

export type DownloadFormat = 'archive' | 'markdown' | 'html' | 'html5' | 'pdf' | 'docx' | 'latex' | 'beamer' | 'context' | 'man' | 'mediawiki' | 'dokuwiki' | 'textile' | 'org' | 'texinfo' | 'opml' | 'docbook' | 'opendocument' | 'odt' | 'rtf' | 'epub' | 'epub3' | 'fb2' | 'asciidoc' | 'icml' | 'slidy' | 'slideous' | 'dzslides' | 'revealjs' | 's5' | 'json' | 'plain' | 'commonmark' | 'commonmark_x' | 'markdown_strict' | 'markdown_phpextra' | 'markdown_github' | 'rst' | 'native' | 'haddock';

export type ExecBody = {
    payload?: unknown;
};

export type ExecResultResponse = {
    data?: unknown;
    effects: Array<unknown>;
    error?: unknown;
    ok: boolean;
};

export type GitChangeItem = {
    path: string;
    status: string;
};

export type GitChangesResponse = {
    files: Array<GitChangeItem>;
};

export type GitCommitItem = {
    author_email: string;
    author_name: string;
    hash: string;
    message: string;
    time: string;
};

export type GitConfigResponse = {
    auth_type: string;
    auto_sync: boolean;
    branch_name: string;
    created_at: string;
    id: string;
    repository_url: string;
    updated_at: string;
};

export type GitHistoryResponse = {
    commits: Array<GitCommitItem>;
};

export type GitStatus = {
    current_branch?: (string) | null;
    has_remote: boolean;
    last_sync?: (string) | null;
    last_sync_commit_hash?: (string) | null;
    last_sync_message?: (string) | null;
    last_sync_status?: (string) | null;
    repository_initialized: boolean;
    sync_enabled: boolean;
    uncommitted_changes: number;
    untracked_files: number;
};

export type GitSyncRequest = {
    force?: (boolean) | null;
    full_scan?: (boolean) | null;
    message?: (string) | null;
    skip_push?: (boolean) | null;
};

export type GitSyncResponse = {
    commit_hash?: (string) | null;
    files_changed: number;
    message: string;
    success: boolean;
};

export type HealthResp = {
    status: string;
};

export type InstallFromUrlBody = {
    token?: (string) | null;
    url: string;
};

export type InstallResponse = {
    id: string;
    version: string;
};

export type KvValueBody = {
    value: unknown;
};

export type KvValueResponse = {
    value: unknown;
};

export type LoginRequest = {
    email: string;
    password: string;
};

export type LoginResponse = {
    access_token: string;
    user: UserResponse;
};

export type ManifestItem = {
    author?: (string) | null;
    config: unknown;
    frontend: unknown;
    id: string;
    mounts: Array<string>;
    name?: (string) | null;
    permissions: Array<string>;
    repository?: (string) | null;
    scope: string;
    ui: unknown;
    version: string;
};

export type MaterializeResponse = {
    created: number;
};

export type OutgoingLink = {
    document_id: string;
    document_type: string;
    file_path?: (string) | null;
    link_text?: (string) | null;
    link_type: string;
    position_end?: (number) | null;
    position_start?: (number) | null;
    title: string;
};

export type OutgoingLinksResponse = {
    links: Array<OutgoingLink>;
    total_count: number;
};

export type PlaceholderItemPayload = {
    code: string;
    id: string;
    kind: string;
};

export type PublicDocumentSummary = {
    id: string;
    published_at: string;
    title: string;
    updated_at: string;
};

export type PublishResponse = {
    public_url: string;
    slug: string;
};

export type RecordsResponse = {
    items: Array<unknown>;
};

export type RegisterRequest = {
    email: string;
    name: string;
    password: string;
};

export type RenderManyRequest = {
    items: Array<RenderRequest>;
};

export type RenderManyResponse = {
    items: Array<RenderResponseBody>;
};

export type RenderOptionsPayload = {
    absolute_attachments?: (boolean) | null;
    base_origin?: (string) | null;
    doc_id?: (string) | null;
    features?: Array<string> | null;
    flavor?: (string) | null;
    sanitize?: (boolean) | null;
    theme?: (string) | null;
    token?: (string) | null;
};

export type RenderRequest = {
    options?: RenderOptionsPayload;
    text: string;
};

export type RenderResponseBody = {
    hash: string;
    html: string;
    placeholders?: Array<PlaceholderItemPayload>;
};

export type SearchResult = {
    document_type: string;
    id: string;
    path?: (string) | null;
    title: string;
    updated_at: string;
};

export type ShareBrowseResponse = {
    tree: Array<ShareBrowseTreeItem>;
};

export type ShareBrowseTreeItem = {
    created_at: string;
    id: string;
    parent_id?: (string) | null;
    title: string;
    type: string;
    updated_at: string;
};

export type ShareDocumentResponse = {
    content?: (string) | null;
    id: string;
    permission: string;
    title: string;
};

export type ShareItem = {
    expires_at?: (string) | null;
    id: string;
    /**
     * If present, this document share was materialized from a folder share
     */
    parent_share_id?: (string) | null;
    permission: string;
    /**
     * document | folder
     */
    scope: string;
    token: string;
    url: string;
};

export type SnapshotDiffBaseParam = 'auto' | 'current' | 'previous';

export type SnapshotDiffKind = 'current' | 'snapshot';

export type SnapshotDiffResponse = {
    base: SnapshotDiffSideResponse;
    diff: TextDiffResult;
    target: SnapshotDiffSideResponse;
};

export type SnapshotDiffSideResponse = {
    kind: SnapshotDiffKind;
    markdown: string;
    snapshot?: ((SnapshotSummary) | null);
};

export type SnapshotListResponse = {
    items: Array<SnapshotSummary>;
};

export type SnapshotRestoreResponse = {
    snapshot: SnapshotSummary;
};

export type SnapshotSummary = {
    byte_size: number;
    content_hash: string;
    created_at: string;
    created_by?: (string) | null;
    document_id: string;
    id: string;
    kind: string;
    label: string;
    notes?: (string) | null;
};

export type TagItem = {
    count: number;
    name: string;
};

export type TextDiffLine = {
    content: string;
    line_type: TextDiffLineType;
    new_line_number?: (number) | null;
    old_line_number?: (number) | null;
};

export type TextDiffLineType = 'added' | 'deleted' | 'context';

export type TextDiffResult = {
    diff_lines: Array<TextDiffLine>;
    file_path: string;
    new_content?: (string) | null;
    old_content?: (string) | null;
};

export type UninstallBody = {
    id: string;
};

export type UpdateDocumentContentRequest = {
    content: string;
};

export type UpdateDocumentRequest = {
    parent_id?: (string) | null;
    title?: (string) | null;
};

export type UpdateGitConfigRequest = {
    auth_data?: unknown;
    auth_type?: (string) | null;
    auto_sync?: (boolean) | null;
    branch_name?: (string) | null;
    repository_url?: (string) | null;
};

export type UpdateRecordBody = {
    patch: unknown;
};

export type UpdateUserShortcutRequest = {
    bindings?: {
        [key: string]: unknown;
    };
    leader_key?: (string) | null;
};

export type UploadFileMultipart = {
    /**
     * Target document ID
     */
    document_id: string;
    /**
     * File to upload
     */
    file: Blob | File;
};

export type UploadFileResponse = {
    content_type?: (string) | null;
    filename: string;
    id: string;
    size: number;
    url: string;
};

export type UserResponse = {
    email: string;
    id: string;
    name: string;
};

export type UserShortcutResponse = {
    bindings: {
        [key: string]: unknown;
    };
    leader_key?: (string) | null;
    updated_at?: (string) | null;
};

export type LoginData = {
    requestBody: LoginRequest;
};

export type LoginResponse2 = (LoginResponse);

export type LogoutResponse = (void);

export type MeResponse = (UserResponse);

export type DeleteAccountResponse = (void);

export type RegisterData = {
    requestBody: RegisterRequest;
};

export type RegisterResponse = (UserResponse);

export type ListDocumentsData = {
    /**
     * Search query
     */
    query?: (string) | null;
    /**
     * Filter by document state (active|archived|all)
     */
    state?: (string) | null;
    /**
     * Filter by tag
     */
    tag?: (string) | null;
};

export type ListDocumentsResponse = (DocumentListResponse);

export type CreateDocumentData = {
    requestBody: CreateDocumentRequest;
};

export type CreateDocumentResponse = (Document);

export type SearchDocumentsData = {
    /**
     * Query
     */
    q?: (string) | null;
};

export type SearchDocumentsResponse = (Array<SearchResult>);

export type GetDocumentData = {
    /**
     * Document ID
     */
    id: string;
    /**
     * Share token (optional)
     */
    token?: (string) | null;
};

export type GetDocumentResponse = (Document);

export type DeleteDocumentData = {
    /**
     * Document ID
     */
    id: string;
};

export type DeleteDocumentResponse = (void);

export type UpdateDocumentData = {
    /**
     * Document ID
     */
    id: string;
    requestBody: UpdateDocumentRequest;
};

export type UpdateDocumentResponse = (Document);

export type ArchiveDocumentData = {
    /**
     * Document ID
     */
    id: string;
};

export type ArchiveDocumentResponse = (Document);

export type GetBacklinksData = {
    /**
     * Document ID
     */
    id: string;
};

export type GetBacklinksResponse = (BacklinksResponse);

export type GetDocumentContentData = {
    /**
     * Document ID
     */
    id: string;
};

export type GetDocumentContentResponse = (unknown);

export type UpdateDocumentContentData = {
    /**
     * Document ID
     */
    id: string;
    requestBody: UpdateDocumentContentRequest;
    /**
     * Share token (optional)
     */
    token?: (string) | null;
};

export type UpdateDocumentContentResponse = (Document);

export type DownloadDocumentData = {
    /**
     * Download format (see schema for supported values)
     */
    format?: ((DownloadFormat) | null);
    /**
     * Document ID
     */
    id: string;
    /**
     * Share token (optional)
     */
    token?: (string) | null;
};

export type DownloadDocumentResponse = (DocumentDownloadBinary);

export type GetOutgoingLinksData = {
    /**
     * Document ID
     */
    id: string;
};

export type GetOutgoingLinksResponse = (OutgoingLinksResponse);

export type ListDocumentSnapshotsData = {
    /**
     * Document ID
     */
    id: string;
    /**
     * Maximum number of snapshots to return
     */
    limit?: (number) | null;
    /**
     * Offset for pagination
     */
    offset?: (number) | null;
    /**
     * Share token (optional)
     */
    token?: (string) | null;
};

export type ListDocumentSnapshotsResponse = (SnapshotListResponse);

export type GetDocumentSnapshotDiffData = {
    /**
     * Base comparison to use when compare is not provided (auto|current|previous)
     */
    base?: ((SnapshotDiffBaseParam) | null);
    /**
     * Snapshot ID to compare against (defaults to current document state)
     */
    compare?: (string) | null;
    /**
     * Document ID
     */
    id: string;
    /**
     * Snapshot ID
     */
    snapshotId: string;
    /**
     * Share token (optional)
     */
    token?: (string) | null;
};

export type GetDocumentSnapshotDiffResponse = (SnapshotDiffResponse);

export type DownloadDocumentSnapshotData = {
    /**
     * Document ID
     */
    id: string;
    /**
     * Snapshot ID
     */
    snapshotId: string;
    /**
     * Share token (optional)
     */
    token?: (string) | null;
};

export type DownloadDocumentSnapshotResponse = (DocumentArchiveBinary);

export type RestoreDocumentSnapshotData = {
    /**
     * Document ID
     */
    id: string;
    /**
     * Snapshot ID
     */
    snapshotId: string;
    /**
     * Share token (optional)
     */
    token?: (string) | null;
};

export type RestoreDocumentSnapshotResponse = (SnapshotRestoreResponse);

export type UnarchiveDocumentData = {
    /**
     * Document ID
     */
    id: string;
};

export type UnarchiveDocumentResponse = (Document);

export type UploadFileData = {
    formData: UploadFileMultipart;
};

export type UploadFileResponse2 = (UploadFileResponse);

export type GetFileByNameData = {
    /**
     * Document ID
     */
    documentId: string;
    /**
     * File name
     */
    filename: string;
};

export type GetFileByNameResponse = (Blob | File);

export type GetFileData = {
    /**
     * File ID
     */
    id: string;
};

export type GetFileResponse = (Blob | File);

export type GetChangesResponse = (GitChangesResponse);

export type GetConfigResponse = (((GitConfigResponse) | null));

export type CreateOrUpdateConfigData = {
    requestBody: CreateGitConfigRequest;
};

export type CreateOrUpdateConfigResponse = (GitConfigResponse);

export type DeleteConfigResponse = (void);

export type DeinitRepositoryResponse = (unknown);

export type GetCommitDiffData = {
    /**
     * From
     */
    _from: string;
    /**
     * To
     */
    to: string;
};

export type GetCommitDiffResponse = (Array<TextDiffResult>);

export type GetWorkingDiffResponse = (Array<TextDiffResult>);

export type CheckPathIgnoredData = {
    requestBody: CheckIgnoredRequest;
};

export type CheckPathIgnoredResponse = (unknown);

export type GetGitignorePatternsResponse = (unknown);

export type AddGitignorePatternsData = {
    requestBody: AddPatternsRequest;
};

export type AddGitignorePatternsResponse = (unknown);

export type GetHistoryResponse = (GitHistoryResponse);

export type IgnoreDocumentData = {
    /**
     * Document ID
     */
    id: string;
};

export type IgnoreDocumentResponse = (unknown);

export type IgnoreFolderData = {
    /**
     * Folder ID
     */
    id: string;
};

export type IgnoreFolderResponse = (unknown);

export type InitRepositoryResponse = (unknown);

export type GetStatusResponse = (GitStatus);

export type SyncNowData = {
    requestBody: GitSyncRequest;
};

export type SyncNowResponse = (GitSyncResponse);

export type HealthResponse = (HealthResp);

export type RenderMarkdownData = {
    requestBody: RenderRequest;
};

export type RenderMarkdownResponse = (RenderResponseBody);

export type RenderMarkdownManyData = {
    requestBody: RenderManyRequest;
};

export type RenderMarkdownManyResponse = (RenderManyResponse);

export type ListApiTokensResponse = (Array<ApiTokenItem>);

export type CreateApiTokenData = {
    requestBody: ApiTokenCreateRequest;
};

export type CreateApiTokenResponse = (ApiTokenCreateResponse);

export type RevokeApiTokenData = {
    /**
     * Token ID
     */
    id: string;
};

export type RevokeApiTokenResponse = (void);

export type PluginsInstallFromUrlData = {
    requestBody: InstallFromUrlBody;
};

export type PluginsInstallFromUrlResponse = (InstallResponse);

export type PluginsGetManifestData = {
    /**
     * Share token (optional)
     */
    token?: (string) | null;
};

export type PluginsGetManifestResponse = (Array<ManifestItem>);

export type PluginsUninstallData = {
    requestBody: UninstallBody;
};

export type PluginsUninstallResponse = (void);

export type SseUpdatesResponse = (unknown);

export type GetUserShortcutsResponse = (UserShortcutResponse);

export type UpdateUserShortcutsData = {
    requestBody: UpdateUserShortcutRequest;
};

export type UpdateUserShortcutsResponse = (UserShortcutResponse);

export type PluginsGetKvData = {
    /**
     * Document ID
     */
    docId: string;
    /**
     * Key
     */
    key: string;
    /**
     * Plugin ID
     */
    plugin: string;
    /**
     * Share token
     */
    token?: (string) | null;
};

export type PluginsGetKvResponse = (KvValueResponse);

export type PluginsPutKvData = {
    /**
     * Document ID
     */
    docId: string;
    /**
     * Key
     */
    key: string;
    /**
     * Plugin ID
     */
    plugin: string;
    requestBody: KvValueBody;
    /**
     * Share token
     */
    token?: (string) | null;
};

export type PluginsPutKvResponse = (void);

export type ListRecordsData = {
    /**
     * Document ID
     */
    docId: string;
    /**
     * Record kind
     */
    kind: string;
    /**
     * Limit
     */
    limit?: (number) | null;
    /**
     * Offset
     */
    offset?: (number) | null;
    /**
     * Plugin ID
     */
    plugin: string;
    /**
     * Share token
     */
    token?: (string) | null;
};

export type ListRecordsResponse = (RecordsResponse);

export type PluginsCreateRecordData = {
    /**
     * Document ID
     */
    docId: string;
    /**
     * Record kind
     */
    kind: string;
    /**
     * Plugin ID
     */
    plugin: string;
    requestBody: CreateRecordBody;
    /**
     * Share token
     */
    token?: (string) | null;
};

export type PluginsCreateRecordResponse = (unknown);

export type PluginsExecActionData = {
    /**
     * Action
     */
    action: string;
    /**
     * Plugin ID
     */
    plugin: string;
    requestBody: ExecBody;
    /**
     * Share token
     */
    token?: (string) | null;
};

export type PluginsExecActionResponse = (ExecResultResponse);

export type PluginsDeleteRecordData = {
    /**
     * Record ID
     */
    id: string;
    /**
     * Plugin ID
     */
    plugin: string;
};

export type PluginsDeleteRecordResponse = (void);

export type PluginsUpdateRecordData = {
    /**
     * Record ID
     */
    id: string;
    /**
     * Plugin ID
     */
    plugin: string;
    requestBody: UpdateRecordBody;
};

export type PluginsUpdateRecordResponse = (unknown);

export type GetPublishStatusData = {
    /**
     * Document ID
     */
    id: string;
};

export type GetPublishStatusResponse = (PublishResponse);

export type PublishDocumentData = {
    /**
     * Document ID
     */
    id: string;
};

export type PublishDocumentResponse = (PublishResponse);

export type UnpublishDocumentData = {
    /**
     * Document ID
     */
    id: string;
};

export type UnpublishDocumentResponse = (void);

export type ListUserPublicDocumentsData = {
    /**
     * Owner name
     */
    name: string;
};

export type ListUserPublicDocumentsResponse = (Array<PublicDocumentSummary>);

export type GetPublicByOwnerAndIdData = {
    /**
     * Document ID
     */
    id: string;
    /**
     * Owner name
     */
    name: string;
};

export type GetPublicByOwnerAndIdResponse = (Document);

export type GetPublicContentByOwnerAndIdData = {
    /**
     * Document ID
     */
    id: string;
    /**
     * Owner name
     */
    name: string;
};

export type GetPublicContentByOwnerAndIdResponse = (unknown);

export type CreateShareData = {
    requestBody: CreateShareRequest;
};

export type CreateShareResponse2 = (CreateShareResponse);

export type ListActiveSharesResponse = (Array<ActiveShareItem>);

export type ListApplicableSharesData = {
    /**
     * Document ID
     */
    docId: string;
};

export type ListApplicableSharesResponse = (Array<ApplicableShareItem>);

export type BrowseShareData = {
    /**
     * Share token
     */
    token: string;
};

export type BrowseShareResponse = (ShareBrowseResponse);

export type ListDocumentSharesData = {
    /**
     * Document ID
     */
    id: string;
};

export type ListDocumentSharesResponse = (Array<ShareItem>);

export type MaterializeFolderShareData = {
    /**
     * Folder share token
     */
    token: string;
};

export type MaterializeFolderShareResponse = (MaterializeResponse);

export type ValidateShareTokenData = {
    /**
     * Share token
     */
    token: string;
};

export type ValidateShareTokenResponse = (ShareDocumentResponse);

export type DeleteShareData = {
    /**
     * Share token
     */
    token: string;
};

export type DeleteShareResponse = (void);

export type ListTagsData = {
    /**
     * Filter contains
     */
    q?: (string) | null;
};

export type ListTagsResponse = (Array<TagItem>);

export type AxumWsEntryData = {
    /**
     * Bearer token (JWT or share token)
     */
    authorization?: (string) | null;
    /**
     * Document ID (UUID)
     */
    id: string;
    /**
     * JWT or share token
     */
    token?: (string) | null;
};