// This file is auto-generated by @hey-api/openapi-ts

/**
 * Response for accepting a workspace invitation
 */
export type AcceptInvitationResponse = {
    encryptedKekForInvite?: (string) | null;
    kekVersion?: (number) | null;
    workspaceId: string;
};

export type ActiveShareItem = {
    created_at: string;
    document_id: string;
    document_title: string;
    document_type: string;
    expires_at?: (string) | null;
    id: string;
    parent_share_id?: (string) | null;
    permission: string;
    token: string;
    url: string;
};

export type ApiTokenCreateRequest = {
    name?: (string) | null;
};

export type ApiTokenCreateResponse = {
    created_at: string;
    id: string;
    name: string;
    token: string;
};

export type ApiTokenItem = {
    created_at: string;
    id: string;
    last_used_at?: (string) | null;
    name: string;
    revoked_at?: (string) | null;
};

export type ApplicableShareItem = {
    excluded: boolean;
    permission: string;
    scope: string;
    token: string;
};

export type AuthProviderInfoResponse = {
    authorization_url?: (string) | null;
    client_ids: Array<string>;
    id: string;
    name?: (string) | null;
    redirect_uri?: (string) | null;
    requires_state: boolean;
    scopes?: Array<string>;
};

export type AuthProvidersResponse = {
    providers: Array<AuthProviderInfoResponse>;
};

export type BacklinkInfo = {
    document_id: string;
    document_type: string;
    file_path?: (string) | null;
    link_count: number;
    link_text?: (string) | null;
    link_type: string;
    title: string;
};

export type BacklinksResponse = {
    backlinks: Array<BacklinkInfo>;
    total_count: number;
};

/**
 * DEK payload for document creation
 */
export type CreateDocumentDekPayload = {
    /**
     * Base64 encoded encrypted DEK
     */
    encryptedDek: string;
    /**
     * Key version
     */
    keyVersion?: number;
    /**
     * Base64 encoded nonce
     */
    nonce: string;
};

export type CreateDocumentRequest = {
    dek?: ((CreateDocumentDekPayload) | null);
    /**
     * Base64 encoded encrypted title (for E2EE clients)
     */
    encryptedTitle?: (string) | null;
    /**
     * Base64 encoded nonce for encrypted title
     */
    encryptedTitleNonce?: (string) | null;
    parentId?: (string) | null;
    title?: (string) | null;
    type?: (string) | null;
};

export type CreateGitConfigRequest = {
    auth_data: unknown;
    auth_type: string;
    auto_sync?: (boolean) | null;
    branch_name?: (string) | null;
    repository_url: string;
};

export type CreateRecordBody = {
    data: unknown;
};

export type CreateShareMountRequest = {
    parent_folder_id?: (string) | null;
    token: string;
};

export type CreateShareRequest = {
    /**
     * Base64 encoded share key encrypted with creator's KEK (for URL recovery)
     */
    creatorEncryptedShareKey?: (string) | null;
    /**
     * Base64 encoded nonce for creator_encrypted_share_key
     */
    creatorShareKeyNonce?: (string) | null;
    documentId: string;
    /**
     * Base64 encoded encrypted DEK (encrypted with share key derived from password)
     */
    encryptedDek?: (string) | null;
    expiresAt?: (string) | null;
    /**
     * KDF parameters (e.g., Argon2id settings)
     */
    kdfParams?: unknown;
    permission?: (string) | null;
    /**
     * Base64 encoded salt for key derivation
     */
    salt?: (string) | null;
};

export type CreateShareResponse = {
    token: string;
    url: string;
};

export type CreateWorkspaceInvitationRequest = {
    custom_role_id?: (string) | null;
    email: string;
    expires_at?: (string) | null;
    role_kind: string;
    system_role?: (string) | null;
};

export type CreateWorkspaceRequest = {
    description?: (string) | null;
    icon?: (string) | null;
    name: string;
};

export type CreateWorkspaceRoleRequest = {
    base_role: string;
    description?: (string) | null;
    name: string;
    overrides?: Array<PermissionOverridePayload> | null;
    priority?: (number) | null;
};

export type DeleteKeyVersionResponse = {
    deletedCount: number;
    keyVersion: number;
    workspaceId: string;
};

export type Document = {
    archived_at?: (string) | null;
    archived_by?: (string) | null;
    archived_parent_id?: (string) | null;
    created_at: string;
    created_by?: (string) | null;
    created_by_plugin?: (string) | null;
    desired_path: string;
    encryptedTitle?: (string) | null;
    encryptedTitleNonce?: (string) | null;
    id: string;
    /**
     * Legacy alias for `workspace_id` kept for backward compatibility with older clients.
     */
    owner_id: string;
    parent_id?: (string) | null;
    path?: (string) | null;
    slug: string;
    title: string;
    type: string;
    updated_at: string;
    workspace_id: string;
};

export type DocumentArchiveBinary = Blob | File;

export type DocumentDownloadBinary = Blob | File;

export type DocumentKeyResponse = {
    createdAt: string;
    documentId: string;
    encryptedDek: string;
    keyVersion: number;
    nonce: string;
    updatedAt: string;
};

export type DocumentListResponse = {
    items: Array<Document>;
};

/**
 * Patch operation for document content.
 * For plaintext mode: use `text` field.
 * For E2EE mode: use `encrypted_data` and `nonce` fields instead of `text`.
 */
export type DocumentPatchOperationRequest = {
    /**
     * Base64 encoded encrypted data (for E2EE documents)
     */
    encrypted_data?: (string) | null;
    /**
     * Base64 encoded nonce (required when encrypted_data is provided)
     */
    nonce?: (string) | null;
    offset: number;
    op: 'insert';
    /**
     * Base64 encoded Ed25519 public key (for E2EE documents)
     */
    public_key?: (string) | null;
    /**
     * Base64 encoded Ed25519 signature (for E2EE documents)
     */
    signature?: (string) | null;
    /**
     * Plaintext to insert (for non-E2EE documents)
     */
    text?: (string) | null;
} | {
    length: number;
    offset: number;
    op: 'delete';
} | {
    /**
     * Base64 encoded encrypted data (for E2EE documents)
     */
    encrypted_data?: (string) | null;
    length: number;
    /**
     * Base64 encoded nonce (required when encrypted_data is provided)
     */
    nonce?: (string) | null;
    offset: number;
    op: 'replace';
    /**
     * Base64 encoded Ed25519 public key (for E2EE documents)
     */
    public_key?: (string) | null;
    /**
     * Base64 encoded Ed25519 signature (for E2EE documents)
     */
    signature?: (string) | null;
    /**
     * Plaintext replacement (for non-E2EE documents)
     */
    text?: (string) | null;
};

export namespace DocumentPatchOperationRequest {
    export enum op {
        INSERT = 'insert'
    }
}

/**
 * Tag entry in document tags response
 */
export type DocumentTagEntry = {
    createdAt: string;
    /**
     * Base64 encoded deterministically encrypted tag name
     */
    encryptedName: string;
    id: string;
};

/**
 * Response for GET /api/documents/{id}/tags
 */
export type DocumentTagsResponse = {
    tags: Array<DocumentTagEntry>;
};

export type DownloadDocumentQuery = {
    format?: DownloadFormat;
    token?: (string) | null;
};

export type DownloadFormat = 'archive' | 'markdown' | 'html' | 'html5' | 'pdf' | 'docx' | 'latex' | 'beamer' | 'context' | 'man' | 'mediawiki' | 'dokuwiki' | 'textile' | 'org' | 'texinfo' | 'opml' | 'docbook' | 'opendocument' | 'odt' | 'rtf' | 'epub' | 'epub3' | 'fb2' | 'asciidoc' | 'icml' | 'slidy' | 'slideous' | 'dzslides' | 'revealjs' | 's5' | 'json' | 'plain' | 'commonmark' | 'commonmark_x' | 'markdown_strict' | 'markdown_phpextra' | 'markdown_github' | 'rst' | 'native' | 'haddock';

export type DownloadWorkspaceQuery = {
    format?: DownloadFormat;
};

export type DuplicateDocumentRequest = {
    parent_id?: (string) | null;
    title?: (string) | null;
};

/**
 * Encrypted DEK for a document (request).
 */
export type EncryptedDekRequest = {
    /**
     * Base64-encoded encrypted DEK.
     */
    encryptedDek: string;
    /**
     * Base64-encoded nonce.
     */
    nonce: string;
};

export type EncryptedPrivateKeyResponse = {
    createdAt: string;
    encryptedPrivateKey: string;
    nonce: string;
    updatedAt: string;
};

/**
 * Single encrypted tag in request
 */
export type EncryptedTagInput = {
    /**
     * Base64 encoded deterministically encrypted tag name
     */
    encryptedName: string;
};

/**
 * Encrypted update entry for E2EE documents
 */
export type EncryptedUpdateEntry = {
    /**
     * Base64 encoded encrypted update data
     */
    data: string;
    /**
     * Base64 encoded nonce for decryption
     */
    nonce?: (string) | null;
    /**
     * Base64 encoded public key of the signer
     */
    publicKey?: (string) | null;
    /**
     * Sequence number of the update
     */
    seq: number;
    /**
     * Base64 encoded signature
     */
    signature?: (string) | null;
};

export type EncryptionStatusResponse = {
    isSetupCompleted: boolean;
};

/**
 * Response for GET /api/documents/{id}/content (E2EE encrypted)
 */
export type GetContentResponse = {
    /**
     * Base64 encoded encrypted Yjs snapshot bytes
     */
    content: string;
    /**
     * Base64 encoded nonce for decryption
     */
    nonce?: (string) | null;
    /**
     * Sequence number at which the snapshot was taken
     */
    seqAtSnapshot?: (number) | null;
    /**
     * Pending encrypted updates since the snapshot
     */
    updates?: Array<EncryptedUpdateEntry> | null;
};

export type GitConfigResponse = {
    auth_type: string;
    auto_sync: boolean;
    branch_name: string;
    created_at: string;
    /**
     * E2EE encrypted auth data (only present for E2EE clients)
     */
    encrypted_auth_data?: unknown;
    id: string;
    remote_check?: ((GitRemoteCheckResponse) | null);
    repository_url: string;
    updated_at: string;
};

export type GitRemoteCheckResponse = {
    message: string;
    ok: boolean;
    reason?: (string) | null;
};

export type HealthResp = {
    status: string;
};

export type IngestBatchRequest = {
    events: Array<IngestEventRequest>;
};

export type IngestEventRequest = {
    backend?: (string) | null;
    content_hash?: (string) | null;
    kind: IngestKindParam;
    payload?: unknown;
    repo_path: string;
};

export type IngestKindParam = 'upsert' | 'delete';

export type InstallFromUrlBody = {
    token?: (string) | null;
    url: string;
};

export type InstallResponse = {
    id: string;
    version: string;
};

export type KdfParamsResponse = {
    iterations?: (number) | null;
    memory?: (number) | null;
    parallelism?: (number) | null;
};

export type KvValueBody = {
    value: unknown;
};

export type KvValueResponse = {
    value: unknown;
};

/**
 * Response for listing files in a document.
 * Returns encrypted metadata for client-side decryption to build file map.
 */
export type ListFileResponse = {
    /**
     * SHA256 hash of encrypted file content
     */
    encryptedHash?: (string) | null;
    /**
     * Base64 encoded encrypted metadata (contains filename, logicalPath, mimeType)
     */
    encryptedMetadata?: (string) | null;
    /**
     * Base64 encoded nonce for encrypted metadata
     */
    encryptedMetadataNonce?: (string) | null;
    id: string;
    /**
     * File size in bytes
     */
    size: number;
};

/**
 * Response for GET /api/tags
 */
export type ListTagsResponse = {
    tags: Array<TagEntry>;
};

export type LoginRequest = {
    email: string;
    password: string;
    remember_me?: boolean;
};

export type LoginResponse = {
    access_token: string;
    user: UserResponse;
};

export type ManifestItem = {
    author?: (string) | null;
    backend: unknown;
    config: unknown;
    frontend: unknown;
    id: string;
    mounts: Array<string>;
    name?: (string) | null;
    permissions: Array<string>;
    renderers: unknown;
    repository?: (string) | null;
    scope: string;
    ui: unknown;
    version: string;
};

export type MasterKeyBackupResponse = {
    createdAt: string;
    encryptedKey: string;
    kdfParams: KdfParamsResponse;
    kdfType: string;
    salt: string;
    updatedAt: string;
};

export type MaterializeResponse = {
    created: number;
};

/**
 * Encrypted KEK for a workspace member (request).
 */
export type MemberEncryptedKekRequest = {
    /**
     * Base64-encoded encrypted KEK.
     */
    encryptedKek: string;
    /**
     * User ID.
     */
    userId: string;
};

/**
 * Request to migrate user data to E2EE.
 */
export type MigrateRequest = {
    /**
     * Document DEKs (Data Encryption Keys).
     * Maps document_id (string) -> base64-encoded raw DEK.
     */
    documentDeks: {
        [key: string]: string;
    };
    /**
     * Encrypted DEKs to store for each document.
     * Maps document_id (string) -> encrypted DEK with nonce.
     */
    encryptedDocumentDeks: {
        [key: string]: EncryptedDekRequest;
    };
    /**
     * Encrypted workspace KEKs to store for each member.
     * Maps workspace_id (string) -> array of member encrypted KEKs.
     */
    encryptedWorkspaceKeks: {
        [key: string]: Array<MemberEncryptedKekRequest>;
    };
    /**
     * Workspace KEKs (Key Encryption Keys).
     * Maps workspace_id (string) -> base64-encoded raw KEK.
     */
    workspaceKeks: {
        [key: string]: string;
    };
};

/**
 * Response for migration result.
 */
export type MigrationResponse = {
    /**
     * Number of documents encrypted.
     */
    documentsEncrypted: number;
    /**
     * Number of files with encrypted metadata.
     */
    filesEncrypted: number;
    /**
     * Migration status.
     */
    status: string;
    /**
     * Total number of Yjs updates cleared.
     */
    updatesCleared: number;
};

export type NeedsMigrationResponse = {
    needsMigration: boolean;
};

export type OAuthLoginRequest = {
    code?: (string) | null;
    credential?: (string) | null;
    redirect_uri?: (string) | null;
    remember_me?: boolean;
    state?: (string) | null;
};

export type OAuthStateResponse = {
    state: string;
};

export type OutgoingLink = {
    document_id: string;
    document_type: string;
    file_path?: (string) | null;
    link_text?: (string) | null;
    link_type: string;
    position_end?: (number) | null;
    position_start?: (number) | null;
    title: string;
};

export type OutgoingLinksResponse = {
    links: Array<OutgoingLink>;
    total_count: number;
};

export type PatchDocumentContentRequest = {
    /**
     * Patch operations. Each operation can be either plaintext (using `text` field)
     * or encrypted (using `encryptedData` and `nonce` fields).
     */
    operations?: Array<DocumentPatchOperationRequest>;
    /**
     * Base64 encoded signature for integrity verification (optional for E2EE)
     */
    signature?: (string) | null;
};

export type PermissionOverridePayload = {
    allowed: boolean;
    permission: string;
};

export type PublicDocumentSummary = {
    id: string;
    published_at: string;
    title: string;
    updated_at: string;
};

/**
 * Request to publish a document. For E2EE workspaces, plaintext title and content
 * must be provided so public pages can be rendered without decryption.
 */
export type PublishRequest = {
    /**
     * Plaintext content (required for E2EE mode)
     */
    plaintextContent?: (string) | null;
    /**
     * Plaintext title (required for E2EE mode)
     */
    plaintextTitle?: (string) | null;
};

export type PublishResponse = {
    public_url: string;
    slug: string;
};

export type RecordsResponse = {
    items: Array<unknown>;
};

export type RefreshResponse = {
    access_token: string;
};

export type RegisterPublicKeyRequest = {
    /**
     * Key type (x25519, ed25519, or ecdh-p256)
     */
    keyType: string;
    /**
     * Base64 encoded public key
     */
    publicKey: string;
};

export type RegisterRequest = {
    email: string;
    name: string;
    password: string;
};

/**
 * Request body for document DEK rotation
 */
export type RotateDocumentKeyRequest = {
    /**
     * Base64 encoded new encrypted DEK
     */
    encryptedDek: string;
    /**
     * Base64 encoded nonce
     */
    nonce: string;
};

/**
 * Response for document DEK rotation
 */
export type RotateDocumentKeyResponse = {
    documentId: string;
    newKeyVersion: number;
};

/**
 * Request body for KEK rotation
 */
export type RotateWorkspaceKeyRequest = {
    /**
     * Encrypted KEKs for all workspace members
     */
    memberKeys: Array<RotationMemberKey>;
};

/**
 * Response for KEK rotation
 */
export type RotateWorkspaceKeyResponse = {
    keysUpdated: number;
    newKeyVersion: number;
    workspaceId: string;
};

/**
 * A single member's encrypted KEK for key rotation
 */
export type RotationMemberKey = {
    /**
     * Base64 encoded encrypted KEK for this member
     */
    encryptedKek: string;
    /**
     * User ID of the member
     */
    userId: string;
};

export type SessionResponse = {
    created_at: string;
    current: boolean;
    expires_at: string;
    id: string;
    ip_address?: (string) | null;
    last_seen_at: string;
    remember_me: boolean;
    user_agent?: (string) | null;
    workspace_id: string;
};

export type ShareBrowseResponse = {
    tree: Array<ShareBrowseTreeItem>;
};

export type ShareBrowseTreeItem = {
    created_at: string;
    id: string;
    parent_id?: (string) | null;
    title: string;
    type: string;
    updated_at: string;
};

export type ShareDocumentResponse = {
    content?: (string) | null;
    /**
     * Base64 encoded encrypted DEK (encrypted with share key)
     */
    encryptedDek?: (string) | null;
    id: string;
    /**
     * KDF parameters for password-protected shares
     */
    kdfParams?: unknown;
    permission: string;
    /**
     * Base64 encoded salt for password-protected shares
     */
    salt?: (string) | null;
    title: string;
};

export type ShareItem = {
    /**
     * Base64 encoded share key encrypted with creator's KEK (for URL recovery)
     */
    creatorEncryptedShareKey?: (string) | null;
    /**
     * Base64 encoded nonce for creator_encrypted_share_key
     */
    creatorShareKeyNonce?: (string) | null;
    expiresAt?: (string) | null;
    id: string;
    parentShareId?: (string) | null;
    permission: string;
    scope: string;
    token: string;
    url: string;
};

export type ShareKeyResponse = {
    createdAt: string;
    encryptedDek: string;
    isPasswordProtected: boolean;
    kdfParams?: ((KdfParamsResponse) | null);
    salt?: (string) | null;
    shareId: string;
};

export type ShareMountItem = {
    created_at: string;
    id: string;
    parent_folder_id?: (string) | null;
    permission: string;
    target_document_id: string;
    target_document_type: string;
    target_title: string;
    token: string;
};

/**
 * Response for share salt challenge (for password-protected shares)
 */
export type ShareSaltResponse = {
    /**
     * KDF parameters for key derivation (only present if password-protected)
     */
    kdfParams?: unknown;
    /**
     * Whether this share is password-protected
     */
    passwordProtected: boolean;
    /**
     * Base64 encoded salt for key derivation (only present if password-protected)
     */
    salt?: (string) | null;
};

/**
 * Response for GET /api/documents/{id}/snapshots/{snapshotId}
 * - For E2EE documents: content is encrypted, nonce is present
 * - For non-E2EE documents: content is plaintext Yjs state, nonce is None
 */
export type SnapshotDetailResponse = {
    /**
     * Base64 encoded Yjs snapshot (encrypted for E2EE, plaintext for non-E2EE)
     */
    content: string;
    createdAt: string;
    id: string;
    /**
     * Base64 encoded nonce (present for E2EE documents)
     */
    nonce?: (string) | null;
};

export type SnapshotDiffBaseParam = 'auto' | 'current' | 'previous';

export type SnapshotDiffKind = 'current' | 'snapshot';

export type SnapshotDiffResponse = {
    base: SnapshotDiffSideResponse;
    diff: TextDiffResult;
    target: SnapshotDiffSideResponse;
};

export type SnapshotDiffSideResponse = {
    kind: SnapshotDiffKind;
    markdown: string;
    snapshot?: ((SnapshotSummary) | null);
};

export type SnapshotListResponse = {
    items: Array<SnapshotSummary>;
};

export type SnapshotRestoreResponse = {
    snapshot: SnapshotSummary;
};

export type SnapshotSummary = {
    byte_size: number;
    content_hash: string;
    created_at: string;
    created_by?: (string) | null;
    document_id: string;
    id: string;
    kind: string;
    label: string;
    nonce?: (string) | null;
    notes?: (string) | null;
    signature?: (string) | null;
};

export type StoreDocumentKeyRequest = {
    /**
     * Base64 encoded encrypted DEK
     */
    encryptedDek: string;
    /**
     * Key version
     */
    keyVersion: number;
    /**
     * Base64 encoded nonce
     */
    nonce: string;
};

export type StoreEncryptedPrivateKeyRequest = {
    /**
     * Base64 encoded encrypted private key
     */
    encryptedPrivateKey: string;
    /**
     * Base64 encoded nonce
     */
    nonce: string;
};

export type StoreMasterKeyBackupRequest = {
    /**
     * Base64 encoded encrypted master key
     */
    encryptedKey: string;
    kdfParams: KdfParamsResponse;
    /**
     * KDF type (e.g., "argon2id", "pbkdf2")
     */
    kdfType: string;
    /**
     * Base64 encoded salt
     */
    salt: string;
};

export type StorePasswordProtectedShareKeyRequest = {
    /**
     * Base64 encoded encrypted DEK
     */
    encryptedDek: string;
    kdfParams: KdfParamsResponse;
    /**
     * Base64 encoded salt
     */
    salt: string;
};

export type StoreShareKeyRequest = {
    /**
     * Base64 encoded encrypted DEK
     */
    encryptedDek: string;
};

export type StoreWorkspaceKeyRequest = {
    /**
     * Base64 encoded encrypted KEK
     */
    encryptedKek: string;
    /**
     * Key version (for key rotation tracking)
     */
    keyVersion: number;
};

export type SwitchWorkspaceResponse = {
    access_token: string;
};

/**
 * Tag entry in list response (E2EE format)
 */
export type TagEntry = {
    documentCount: number;
    /**
     * Base64 encoded deterministically encrypted tag name
     */
    encryptedName: string;
};

export type TextDiffLine = {
    content: string;
    line_type: TextDiffLineType;
    new_line_number?: (number) | null;
    old_line_number?: (number) | null;
};

export type TextDiffLineType = 'added' | 'deleted' | 'context';

export type TextDiffResult = {
    diff_lines: Array<TextDiffLine>;
    file_path: string;
    new_content?: (string) | null;
    old_content?: (string) | null;
};

export type UninstallBody = {
    id: string;
};

export type UpdateDocumentContentRequest = {
    /**
     * Document content (plaintext or Base64-encoded encrypted Yjs state for E2EE)
     */
    content: string;
    /**
     * Base64 encoded nonce (required for E2EE content)
     */
    nonce?: (string) | null;
    /**
     * Base64 encoded signature for integrity verification (optional for E2EE)
     */
    signature?: (string) | null;
};

export type UpdateDocumentRequest = {
    parent_id?: (string) | null;
    title?: (string) | null;
};

/**
 * Request for PUT /api/documents/{id}/tags
 */
export type UpdateDocumentTagsRequest = {
    encryptedTags: Array<EncryptedTagInput>;
};

/**
 * Request to update invitation with encrypted KEK
 */
export type UpdateInvitationKekRequest = {
    /**
     * Base64 encoded encrypted KEK (encrypted with key derived from invitation token)
     */
    encryptedKekForInvite: string;
    /**
     * KEK version at the time of invitation
     */
    kekVersion: number;
};

export type UpdateMemberRoleRequest = {
    custom_role_id?: (string) | null;
    role_kind: string;
    system_role?: (string) | null;
};

export type UpdateRecordBody = {
    patch: unknown;
};

export type UpdateUserShortcutRequest = {
    bindings?: {
        [key: string]: unknown;
    };
    leader_key?: (string) | null;
};

export type UpdateWorkspaceRequest = {
    description?: (string) | null;
    icon?: (string) | null;
    name?: (string) | null;
};

export type UpdateWorkspaceRoleRequest = {
    base_role?: (string) | null;
    description?: (string) | null;
    name?: (string) | null;
    overrides?: Array<PermissionOverridePayload> | null;
    priority?: (number) | null;
};

/**
 * Multipart upload schema for OpenAPI
 */
export type UploadFileMultipart = {
    /**
     * Encrypted file binary (.rme format)
     */
    file: Blob | File;
    /**
     * JSON metadata containing encrypted file metadata
     */
    metadata?: (string) | null;
};

/**
 * Response for file upload (E2EE format per design)
 */
export type UploadFileResponse = {
    /**
     * SHA256 hash of encrypted file content
     */
    encryptedHash: string;
    /**
     * Storage filename (UUID, for building relative paths)
     */
    filename: string;
    id: string;
    size: number;
    /**
     * URL to access the file (relative or absolute)
     */
    url: string;
};

export type UserPublicKeyResponse = {
    createdAt: string;
    keyType: string;
    publicKey: string;
    updatedAt: string;
};

export type UserResponse = {
    active_workspace?: ((WorkspaceMembershipResponse) | null);
    active_workspace_id?: (string) | null;
    active_workspace_permissions?: Array<string>;
    email: string;
    id: string;
    name: string;
    workspaces: Array<WorkspaceMembershipResponse>;
};

export type UserShortcutResponse = {
    bindings: {
        [key: string]: unknown;
    };
    leader_key?: (string) | null;
    updated_at?: (string) | null;
};

export type WorkspaceInvitationResponse = {
    accepted_at?: (string) | null;
    accepted_by?: (string) | null;
    created_at: string;
    custom_role_id?: (string) | null;
    email: string;
    encryptedKekForInvite?: (string) | null;
    expires_at?: (string) | null;
    id: string;
    invited_by: string;
    kekVersion?: (number) | null;
    revoked_at?: (string) | null;
    role_kind: string;
    system_role?: (string) | null;
    token: string;
    workspace_id: string;
};

export type WorkspaceKeyResponse = {
    createdAt: string;
    encryptedKek: string;
    id: string;
    keyVersion: number;
    userId: string;
    workspaceId: string;
};

export type WorkspaceKeyVersionResponse = {
    keyVersion?: (number) | null;
    workspaceId: string;
};

export type WorkspaceMemberResponse = {
    custom_role_id?: (string) | null;
    email: string;
    is_default: boolean;
    name: string;
    role_kind: string;
    system_role?: (string) | null;
    user_id: string;
    workspace_id: string;
};

export type WorkspaceMembershipResponse = {
    custom_role_id?: (string) | null;
    description?: (string) | null;
    icon?: (string) | null;
    id: string;
    is_default: boolean;
    is_personal: boolean;
    name: string;
    role_kind: string;
    slug: string;
    system_role?: (string) | null;
};

export type WorkspacePermissionsResponse = {
    permissions: Array<string>;
    workspace_id: string;
};

export type WorkspaceResponse = {
    custom_role_id?: (string) | null;
    description?: (string) | null;
    icon?: (string) | null;
    id: string;
    is_default: boolean;
    is_personal: boolean;
    name: string;
    role_kind: string;
    slug: string;
    system_role?: (string) | null;
};

export type WorkspaceRoleResponse = {
    base_role: string;
    description?: (string) | null;
    id: string;
    name: string;
    overrides: Array<PermissionOverridePayload>;
    priority: number;
    workspace_id: string;
};

export type LoginData = {
    requestBody: LoginRequest;
};

export type LoginResponse2 = (LoginResponse);

export type LogoutResponse = (void);

export type MeResponse = (UserResponse);

export type DeleteAccountResponse = (void);

export type OauthLoginData = {
    /**
     * OAuth provider identifier (e.g., google)
     */
    provider: string;
    requestBody: OAuthLoginRequest;
};

export type OauthLoginResponse = (LoginResponse);

export type OauthStateData = {
    /**
     * OAuth provider identifier
     */
    provider: string;
};

export type OauthStateResponse = (OAuthStateResponse);

export type ListOauthProvidersResponse = (AuthProvidersResponse);

export type RefreshSessionResponse = (RefreshResponse);

export type RegisterData = {
    requestBody: RegisterRequest;
};

export type RegisterResponse = (UserResponse);

export type ListSessionsResponse = (Array<SessionResponse>);

export type RevokeSessionData = {
    /**
     * Session ID
     */
    id: string;
};

export type RevokeSessionResponse = (void);

export type ListDocumentsData = {
    /**
     * Filter by document state (active|archived|all)
     */
    state?: (string) | null;
    /**
     * Filter by encrypted tag (Base64 encoded)
     */
    tag?: (string) | null;
};

export type ListDocumentsResponse = (DocumentListResponse);

export type CreateDocumentData = {
    requestBody: CreateDocumentRequest;
};

export type CreateDocumentResponse = (Document);

export type ListFilesData = {
    /**
     * Document ID
     */
    docId: string;
};

export type ListFilesResponse = (Array<ListFileResponse>);

export type UploadFileData = {
    /**
     * Document ID
     */
    docId: string;
    formData: UploadFileMultipart;
};

export type UploadFileResponse2 = (UploadFileResponse);

export type GetDocumentData = {
    /**
     * Document ID
     */
    id: string;
    /**
     * Share token (optional)
     */
    token?: (string) | null;
};

export type GetDocumentResponse = (Document);

export type DeleteDocumentData = {
    /**
     * Document ID
     */
    id: string;
};

export type DeleteDocumentResponse = (void);

export type UpdateDocumentData = {
    /**
     * Document ID
     */
    id: string;
    requestBody: UpdateDocumentRequest;
};

export type UpdateDocumentResponse = (Document);

export type ArchiveDocumentData = {
    /**
     * Document ID
     */
    id: string;
};

export type ArchiveDocumentResponse = (Document);

export type GetBacklinksData = {
    /**
     * Document ID
     */
    id: string;
};

export type GetBacklinksResponse = (BacklinksResponse);

export type GetDocumentContentData = {
    /**
     * Document ID
     */
    id: string;
};

export type GetDocumentContentResponse = (GetContentResponse);

export type UpdateDocumentContentData = {
    /**
     * Document ID
     */
    id: string;
    requestBody: UpdateDocumentContentRequest;
    /**
     * Share token (optional)
     */
    token?: (string) | null;
};

export type UpdateDocumentContentResponse = (Document);

export type PatchDocumentContentData = {
    /**
     * Document ID
     */
    id: string;
    requestBody: PatchDocumentContentRequest;
    /**
     * Share token (optional)
     */
    token?: (string) | null;
};

export type PatchDocumentContentResponse = (Document);

export type DownloadDocumentData = {
    /**
     * Download format (see schema for supported values)
     */
    format?: ((DownloadFormat) | null);
    /**
     * Document ID
     */
    id: string;
    /**
     * Share token (optional)
     */
    token?: (string) | null;
};

export type DownloadDocumentResponse = (DocumentDownloadBinary);

export type DuplicateDocumentData = {
    /**
     * Document ID
     */
    id: string;
    requestBody: DuplicateDocumentRequest;
};

export type DuplicateDocumentResponse = (Document);

export type GetDocumentKeyData = {
    /**
     * Document ID
     */
    id: string;
};

export type GetDocumentKeyResponse = (DocumentKeyResponse);

export type StoreDocumentKeyData = {
    /**
     * Document ID
     */
    id: string;
    requestBody: StoreDocumentKeyRequest;
};

export type StoreDocumentKeyResponse = (DocumentKeyResponse);

export type RotateDocumentKeyData = {
    /**
     * Document ID
     */
    id: string;
    requestBody: RotateDocumentKeyRequest;
};

export type RotateDocumentKeyResponse2 = (RotateDocumentKeyResponse);

export type GetOutgoingLinksData = {
    /**
     * Document ID
     */
    id: string;
};

export type GetOutgoingLinksResponse = (OutgoingLinksResponse);

export type ListDocumentSnapshotsData = {
    /**
     * Document ID
     */
    id: string;
    /**
     * Maximum number of snapshots to return
     */
    limit?: (number) | null;
    /**
     * Offset for pagination
     */
    offset?: (number) | null;
    /**
     * Share token (optional)
     */
    token?: (string) | null;
};

export type ListDocumentSnapshotsResponse = (SnapshotListResponse);

export type GetDocumentSnapshotData = {
    /**
     * Document ID
     */
    id: string;
    /**
     * Snapshot ID
     */
    snapshotId: string;
    /**
     * Share token (optional)
     */
    token?: (string) | null;
};

export type GetDocumentSnapshotResponse = (SnapshotDetailResponse);

export type GetDocumentSnapshotDiffData = {
    /**
     * Base comparison to use when compare is not provided (auto|current|previous)
     */
    base?: ((SnapshotDiffBaseParam) | null);
    /**
     * Snapshot ID to compare against (defaults to current document state)
     */
    compare?: (string) | null;
    /**
     * Document ID
     */
    id: string;
    /**
     * Snapshot ID
     */
    snapshotId: string;
    /**
     * Share token (optional)
     */
    token?: (string) | null;
};

export type GetDocumentSnapshotDiffResponse = (SnapshotDiffResponse);

export type DownloadDocumentSnapshotData = {
    /**
     * Document ID
     */
    id: string;
    /**
     * Snapshot ID
     */
    snapshotId: string;
    /**
     * Share token (optional)
     */
    token?: (string) | null;
};

export type DownloadDocumentSnapshotResponse = (DocumentArchiveBinary);

export type RestoreDocumentSnapshotData = {
    /**
     * Document ID
     */
    id: string;
    /**
     * Snapshot ID
     */
    snapshotId: string;
    /**
     * Share token (optional)
     */
    token?: (string) | null;
};

export type RestoreDocumentSnapshotResponse = (SnapshotRestoreResponse);

export type GetDocumentTagsData = {
    /**
     * Document ID
     */
    id: string;
};

export type GetDocumentTagsResponse = (DocumentTagsResponse);

export type UpdateDocumentTagsData = {
    /**
     * Document ID
     */
    id: string;
    requestBody: UpdateDocumentTagsRequest;
};

export type UpdateDocumentTagsResponse = (DocumentTagsResponse);

export type UnarchiveDocumentData = {
    /**
     * Document ID
     */
    id: string;
};

export type UnarchiveDocumentResponse = (Document);

export type GetFileData = {
    /**
     * File ID
     */
    id: string;
};

export type GetFileResponse = (Blob | File);

export type GetConfigResponse = (((GitConfigResponse) | null));

export type CreateOrUpdateConfigData = {
    requestBody: CreateGitConfigRequest;
};

export type CreateOrUpdateConfigResponse = (GitConfigResponse);

export type DeleteConfigResponse = (void);

export type HealthResponse = (HealthResp);

export type ListApiTokensResponse = (Array<ApiTokenItem>);

export type CreateApiTokenData = {
    requestBody: ApiTokenCreateRequest;
};

export type CreateApiTokenResponse = (ApiTokenCreateResponse);

export type RevokeApiTokenData = {
    /**
     * Token ID
     */
    id: string;
};

export type RevokeApiTokenResponse = (void);

export type MigrateData = {
    requestBody: MigrateRequest;
};

export type MigrateResponse = (MigrationResponse);

export type NeedsMigrationResponse2 = (NeedsMigrationResponse);

export type MarkEncryptionSetupCompleteResponse = (void);

export type GetEncryptionStatusResponse = (EncryptionStatusResponse);

export type GetMyPublicKeyResponse = (UserPublicKeyResponse);

export type RegisterPublicKeyData = {
    requestBody: RegisterPublicKeyRequest;
};

export type RegisterPublicKeyResponse = (UserPublicKeyResponse);

export type GetMasterKeyBackupResponse = (MasterKeyBackupResponse);

export type StoreMasterKeyBackupData = {
    requestBody: StoreMasterKeyBackupRequest;
};

export type StoreMasterKeyBackupResponse = (MasterKeyBackupResponse);

export type PluginsInstallFromUrlData = {
    requestBody: InstallFromUrlBody;
};

export type PluginsInstallFromUrlResponse = (InstallResponse);

export type PluginsGetManifestResponse = (Array<ManifestItem>);

export type PluginsUninstallData = {
    requestBody: UninstallBody;
};

export type PluginsUninstallResponse = (void);

export type SseUpdatesResponse = (unknown);

export type GetEncryptedPrivateKeyResponse = (EncryptedPrivateKeyResponse);

export type StoreEncryptedPrivateKeyData = {
    requestBody: StoreEncryptedPrivateKeyRequest;
};

export type StoreEncryptedPrivateKeyResponse = (EncryptedPrivateKeyResponse);

export type GetUserShortcutsResponse = (UserShortcutResponse);

export type UpdateUserShortcutsData = {
    requestBody: UpdateUserShortcutRequest;
};

export type UpdateUserShortcutsResponse = (UserShortcutResponse);

export type PluginsGetAssetData = {
    /**
     * Share token (optional)
     */
    token?: (string) | null;
};

export type PluginsGetAssetResponse = (unknown);

export type PluginsGetKvData = {
    /**
     * Document ID
     */
    docId: string;
    /**
     * Key
     */
    key: string;
    /**
     * Plugin ID
     */
    plugin: string;
};

export type PluginsGetKvResponse = (KvValueResponse);

export type PluginsPutKvData = {
    /**
     * Document ID
     */
    docId: string;
    /**
     * Key
     */
    key: string;
    /**
     * Plugin ID
     */
    plugin: string;
    requestBody: KvValueBody;
};

export type PluginsPutKvResponse = (void);

export type ListRecordsData = {
    /**
     * Document ID
     */
    docId: string;
    /**
     * Record kind
     */
    kind: string;
    /**
     * Limit
     */
    limit?: (number) | null;
    /**
     * Offset
     */
    offset?: (number) | null;
    /**
     * Plugin ID
     */
    plugin: string;
};

export type ListRecordsResponse = (RecordsResponse);

export type PluginsCreateRecordData = {
    /**
     * Document ID
     */
    docId: string;
    /**
     * Record kind
     */
    kind: string;
    /**
     * Plugin ID
     */
    plugin: string;
    requestBody: CreateRecordBody;
};

export type PluginsCreateRecordResponse = (unknown);

export type PluginsDeleteRecordData = {
    /**
     * Record ID
     */
    id: string;
    /**
     * Plugin ID
     */
    plugin: string;
};

export type PluginsDeleteRecordResponse = (void);

export type PluginsUpdateRecordData = {
    /**
     * Record ID
     */
    id: string;
    /**
     * Plugin ID
     */
    plugin: string;
    requestBody: UpdateRecordBody;
};

export type PluginsUpdateRecordResponse = (unknown);

export type GetPublishStatusData = {
    /**
     * Document ID
     */
    id: string;
};

export type GetPublishStatusResponse = (PublishResponse);

export type PublishDocumentData = {
    /**
     * Document ID
     */
    id: string;
    /**
     * Optional plaintext content for E2EE workspaces
     */
    requestBody?: ((PublishRequest) | null);
};

export type PublishDocumentResponse = (PublishResponse);

export type UnpublishDocumentData = {
    /**
     * Document ID
     */
    id: string;
};

export type UnpublishDocumentResponse = (void);

export type ListWorkspacePublicDocumentsData = {
    /**
     * Workspace slug
     */
    slug: string;
};

export type ListWorkspacePublicDocumentsResponse = (Array<PublicDocumentSummary>);

export type GetPublicByWorkspaceAndIdData = {
    /**
     * Document ID
     */
    id: string;
    /**
     * Workspace slug
     */
    slug: string;
};

export type GetPublicByWorkspaceAndIdResponse = (Document);

export type GetPublicContentByWorkspaceAndIdData = {
    /**
     * Document ID
     */
    id: string;
    /**
     * Workspace slug
     */
    slug: string;
};

export type GetPublicContentByWorkspaceAndIdResponse = (unknown);

export type CreateShareData = {
    requestBody: CreateShareRequest;
};

export type CreateShareResponse2 = (CreateShareResponse);

export type ListActiveSharesResponse = (Array<ActiveShareItem>);

export type ListApplicableSharesData = {
    /**
     * Document ID
     */
    docId: string;
};

export type ListApplicableSharesResponse = (Array<ApplicableShareItem>);

export type BrowseShareData = {
    /**
     * Share token
     */
    token: string;
};

export type BrowseShareResponse = (ShareBrowseResponse);

export type ListDocumentSharesData = {
    /**
     * Document ID
     */
    id: string;
};

export type ListDocumentSharesResponse = (Array<ShareItem>);

export type MaterializeFolderShareData = {
    /**
     * Folder share token
     */
    token: string;
};

export type MaterializeFolderShareResponse = (MaterializeResponse);

export type ListShareMountsResponse = (Array<ShareMountItem>);

export type CreateShareMountData = {
    requestBody: CreateShareMountRequest;
};

export type CreateShareMountResponse = (ShareMountItem);

export type DeleteShareMountData = {
    /**
     * Share mount ID
     */
    id: string;
};

export type DeleteShareMountResponse = (void);

export type GetShareSaltData = {
    /**
     * Share token
     */
    token: string;
};

export type GetShareSaltResponse = (ShareSaltResponse);

export type ValidateShareTokenData = {
    /**
     * Share token
     */
    token: string;
};

export type ValidateShareTokenResponse = (ShareDocumentResponse);

export type GetShareKeyData = {
    /**
     * Share ID
     */
    id: string;
};

export type GetShareKeyResponse = (ShareKeyResponse);

export type StoreShareKeyData = {
    /**
     * Share ID
     */
    id: string;
    requestBody: StoreShareKeyRequest;
};

export type StoreShareKeyResponse = (ShareKeyResponse);

export type StorePasswordProtectedShareKeyData = {
    /**
     * Share ID
     */
    id: string;
    requestBody: StorePasswordProtectedShareKeyRequest;
};

export type StorePasswordProtectedShareKeyResponse = (ShareKeyResponse);

export type GetShareSalt1Data = {
    /**
     * Share ID
     */
    id: string;
};

export type GetShareSalt1Response = (ShareSaltResponse);

export type DeleteShareData = {
    /**
     * Share token
     */
    token: string;
};

export type DeleteShareResponse = (void);

export type EnqueueIngestEventsData = {
    requestBody: IngestBatchRequest;
};

export type EnqueueIngestEventsResponse = (unknown);

export type ListTagsData = {
    /**
     * Base64 encoded encrypted tag for exact match filter
     */
    q?: (string) | null;
};

export type ListTagsResponse2 = (ListTagsResponse);

export type GetUserPublicKeyData = {
    /**
     * User ID
     */
    userId: string;
};

export type GetUserPublicKeyResponse = (UserPublicKeyResponse);

export type AcceptInvitationData = {
    /**
     * Invitation token
     */
    token: string;
};

export type AcceptInvitationResponse2 = (AcceptInvitationResponse);

export type ListWorkspacesResponse = (Array<WorkspaceResponse>);

export type CreateWorkspaceData = {
    requestBody: CreateWorkspaceRequest;
};

export type CreateWorkspaceResponse = (WorkspaceResponse);

export type GetWorkspaceDetailData = {
    /**
     * Workspace ID
     */
    id: string;
};

export type GetWorkspaceDetailResponse = (WorkspaceResponse);

export type UpdateWorkspaceData = {
    /**
     * Workspace ID
     */
    id: string;
    requestBody: UpdateWorkspaceRequest;
};

export type UpdateWorkspaceResponse = (WorkspaceResponse);

export type DeleteWorkspaceData = {
    /**
     * Workspace ID
     */
    id: string;
};

export type DeleteWorkspaceResponse = (void);

export type DownloadWorkspaceArchiveData = {
    /**
     * Download format (archive only)
     */
    format?: ((DownloadFormat) | null);
    /**
     * Workspace ID
     */
    id: string;
};

export type DownloadWorkspaceArchiveResponse = (DocumentDownloadBinary);

export type ListInvitationsData = {
    /**
     * Workspace ID
     */
    id: string;
};

export type ListInvitationsResponse = (Array<WorkspaceInvitationResponse>);

export type CreateInvitationData = {
    /**
     * Workspace ID
     */
    id: string;
    requestBody: CreateWorkspaceInvitationRequest;
};

export type CreateInvitationResponse = (WorkspaceInvitationResponse);

export type RevokeInvitationData = {
    /**
     * Workspace ID
     */
    id: string;
    /**
     * Invitation ID
     */
    invitationId: string;
};

export type RevokeInvitationResponse = (WorkspaceInvitationResponse);

export type UpdateInvitationKekData = {
    /**
     * Workspace ID
     */
    id: string;
    /**
     * Invitation ID
     */
    invitationId: string;
    requestBody: UpdateInvitationKekRequest;
};

export type UpdateInvitationKekResponse = (WorkspaceInvitationResponse);

export type ListWorkspaceKeysData = {
    /**
     * Workspace ID
     */
    id: string;
};

export type ListWorkspaceKeysResponse = (Array<WorkspaceKeyResponse>);

export type StoreWorkspaceKeyData = {
    /**
     * Workspace ID
     */
    id: string;
    requestBody: StoreWorkspaceKeyRequest;
};

export type StoreWorkspaceKeyResponse = (WorkspaceKeyResponse);

export type GetMyWorkspaceKeyData = {
    /**
     * Workspace ID
     */
    id: string;
};

export type GetMyWorkspaceKeyResponse = (WorkspaceKeyResponse);

export type RotateWorkspaceKeyData = {
    /**
     * Workspace ID
     */
    id: string;
    requestBody: RotateWorkspaceKeyRequest;
};

export type RotateWorkspaceKeyResponse2 = (RotateWorkspaceKeyResponse);

export type GetWorkspaceKeyVersionData = {
    /**
     * Workspace ID
     */
    id: string;
};

export type GetWorkspaceKeyVersionResponse = (WorkspaceKeyVersionResponse);

export type DeleteKeyVersionData = {
    /**
     * Workspace ID
     */
    id: string;
    /**
     * Key version to delete
     */
    version: number;
};

export type DeleteKeyVersionResponse2 = (DeleteKeyVersionResponse);

export type LeaveWorkspaceData = {
    /**
     * Workspace ID
     */
    id: string;
};

export type LeaveWorkspaceResponse = (void);

export type ListMembersData = {
    /**
     * Workspace ID
     */
    id: string;
};

export type ListMembersResponse = (Array<WorkspaceMemberResponse>);

export type RemoveMemberData = {
    /**
     * Workspace ID
     */
    id: string;
    /**
     * Target user ID
     */
    userId: string;
};

export type RemoveMemberResponse = (void);

export type UpdateMemberRoleData = {
    /**
     * Workspace ID
     */
    id: string;
    requestBody: UpdateMemberRoleRequest;
    /**
     * Target user ID
     */
    userId: string;
};

export type UpdateMemberRoleResponse = (WorkspaceMemberResponse);

export type GetWorkspacePermissionsData = {
    /**
     * Workspace ID
     */
    id: string;
};

export type GetWorkspacePermissionsResponse = (WorkspacePermissionsResponse);

export type ListRolesData = {
    /**
     * Workspace ID
     */
    id: string;
};

export type ListRolesResponse = (Array<WorkspaceRoleResponse>);

export type CreateRoleData = {
    /**
     * Workspace ID
     */
    id: string;
    requestBody: CreateWorkspaceRoleRequest;
};

export type CreateRoleResponse = (WorkspaceRoleResponse);

export type DeleteRoleData = {
    /**
     * Workspace ID
     */
    id: string;
    /**
     * Role ID
     */
    roleId: string;
};

export type DeleteRoleResponse = (void);

export type UpdateRoleData = {
    /**
     * Workspace ID
     */
    id: string;
    requestBody: UpdateWorkspaceRoleRequest;
    /**
     * Role ID
     */
    roleId: string;
};

export type UpdateRoleResponse = (WorkspaceRoleResponse);

export type SwitchWorkspaceData = {
    /**
     * Workspace ID
     */
    id: string;
};

export type SwitchWorkspaceResponse2 = (SwitchWorkspaceResponse);

export type AxumWsEntryData = {
    /**
     * Bearer token (JWT or share token)
     */
    authorization?: (string) | null;
    /**
     * Document ID (UUID)
     */
    id: string;
    /**
     * JWT or share token
     */
    token?: (string) | null;
};