import type { KeyBinding, ShortcutAction } from '@/shared/types/shortcuts'

const chord = (
  key: string,
  modifiers?: { shift?: boolean; alt?: boolean; ctrl?: boolean; meta?: boolean },
): KeyBinding => [
  {
    key,
    shift: modifiers?.shift ?? false,
    alt: modifiers?.alt ?? false,
    ctrl: modifiers?.ctrl ?? false,
    meta: modifiers?.meta ?? false,
  },
]

export const SHORTCUT_ACTIONS: ShortcutAction[] = [
  {
    id: 'global.search.open',
    label: 'Quick search',
    description: 'Open the workspace search and command palette',
    category: 'Navigation',
    scope: 'global',
    default: {
      mac: [chord('k', { meta: true })],
      windows: [chord('k', { ctrl: true })],
    },
  },
  {
    id: 'global.settings.open',
    label: 'Open settings',
    description: 'Navigate to the keyboard shortcuts settings page',
    category: 'Navigation',
    scope: 'global',
    allowInInputs: true,
    default: {
      mac: [chord(',', { meta: true })],
      windows: [chord(',', { ctrl: true })],
    },
  },
  {
    id: 'global.profile.open',
    label: 'Open profile',
    description: 'Jump to your profile page',
    category: 'Navigation',
    scope: 'global',
    allowInInputs: true,
    default: {
      mac: [chord('p', { meta: true, alt: true })],
      windows: [chord('p', { ctrl: true, alt: true })],
    },
  },
  {
    id: 'global.plugins.open',
    label: 'Open plugins',
    description: 'Manage installed plugins',
    category: 'Navigation',
    scope: 'global',
    allowInInputs: true,
    default: {
      mac: [chord('x', { meta: true, alt: true })],
      windows: [chord('x', { ctrl: true, alt: true })],
    },
  },
  {
    id: 'global.file-tree.focus',
    label: 'Focus file tree',
    description: 'Move keyboard focus to the workspace file tree',
    category: 'Navigation',
    scope: 'global',
    default: {
      mac: [chord('e', { meta: true, shift: true })],
      windows: [chord('e', { ctrl: true, shift: true })],
    },
  },
  {
    id: 'file-tree.open.tile',
    label: 'Open in tile',
    description: 'Open the selected file tree document as a tile',
    category: 'Navigation',
    scope: 'global',
    default: {
      mac: [chord('Enter', { shift: true })],
      windows: [chord('Enter', { shift: true })],
    },
  },
  {
    id: 'global.document.new',
    label: 'Create new document',
    description: 'Create a regular workspace document',
    category: 'Workspace',
    scope: 'global',
    allowInInputs: true,
    default: {
      mac: [chord('Enter', { meta: true })],
      windows: [chord('Enter', { ctrl: true })],
    },
  },
  {
    id: 'global.temporary.open',
    label: 'Create temporary document',
    description: 'Start a local-only scratchpad',
    category: 'Workspace',
    scope: 'global',
    allowInInputs: true,
    default: {
      mac: [chord('Enter', { meta: true, shift: true })],
      windows: [chord('Enter', { ctrl: true, shift: true })],
    },
  },
  {
    id: 'global.sidebar.toggle',
    label: 'Toggle sidebar',
    description: 'Collapse or expand the workspace sidebar',
    category: 'Workspace',
    scope: 'global',
    default: {
      mac: [chord('s', { meta: true, alt: true })],
      windows: [chord('s', { ctrl: true, alt: true })],
    },
  },
  {
    id: 'global.theme.toggle',
    label: 'Toggle theme',
    description: 'Switch between light and dark modes',
    category: 'Workspace',
    scope: 'global',
    allowInInputs: true,
    default: {
      mac: [chord('l', { meta: true, alt: true })],
      windows: [chord('l', { ctrl: true, alt: true })],
    },
  },
  {
    id: 'view.mode.editor',
    label: 'Editor view',
    description: 'Switch to editor-only layout',
    category: 'View',
    scope: 'view',
    default: {
      mac: [chord('1', { meta: true })],
      windows: [chord('1', { ctrl: true })],
    },
  },
  {
    id: 'view.mode.split',
    label: 'Editor + preview tiles',
    description: 'Open editor and preview tiles for the current document',
    category: 'View',
    scope: 'view',
    default: {
      mac: [chord('2', { meta: true })],
      windows: [chord('2', { ctrl: true })],
    },
  },
  {
    id: 'view.mode.preview',
    label: 'Preview view',
    description: 'Switch to preview-only layout',
    category: 'View',
    scope: 'view',
    default: {
      mac: [chord('3', { meta: true })],
      windows: [chord('3', { ctrl: true })],
    },
  },
  {
    id: 'view.backlinks.toggle',
    label: 'Open backlinks tile',
    description: 'Open backlinks in a tile',
    category: 'View',
    scope: 'view',
    default: {
      mac: [chord('b', { meta: true, alt: true })],
      windows: [chord('b', { ctrl: true, alt: true })],
    },
  },
  {
    id: 'tiles.split.direction.auto',
    label: 'Tile insertion split: Auto',
    description: 'When opening a document in a new tile, choose split direction automatically',
    category: 'View',
    scope: 'view',
    default: {
      mac: [chord('a', { meta: true, alt: true, shift: true })],
      windows: [chord('a', { ctrl: true, alt: true, shift: true })],
    },
  },
  {
    id: 'tiles.split.direction.row',
    label: 'Tile insertion split: Horizontal',
    description: 'When opening a document in a new tile, split left/right only',
    category: 'View',
    scope: 'view',
    default: {
      mac: [chord('r', { meta: true, alt: true, shift: true })],
      windows: [chord('r', { ctrl: true, alt: true, shift: true })],
    },
  },
  {
    id: 'tiles.split.direction.column',
    label: 'Tile insertion split: Vertical',
    description: 'When opening a document in a new tile, split up/down only',
    category: 'View',
    scope: 'view',
    default: {
      mac: [chord('c', { meta: true, alt: true, shift: true })],
      windows: [chord('c', { ctrl: true, alt: true, shift: true })],
    },
  },
  {
    id: 'tiles.swap.left',
    label: 'Swap tile left',
    description: 'Swap the active tile contents with the tile to the left',
    category: 'View',
    scope: 'view',
    default: {
      mac: [chord('ArrowLeft', { meta: true, alt: true, shift: true })],
      windows: [chord('ArrowLeft', { ctrl: true, alt: true, shift: true })],
    },
  },
  {
    id: 'tiles.swap.right',
    label: 'Swap tile right',
    description: 'Swap the active tile contents with the tile to the right',
    category: 'View',
    scope: 'view',
    default: {
      mac: [chord('ArrowRight', { meta: true, alt: true, shift: true })],
      windows: [chord('ArrowRight', { ctrl: true, alt: true, shift: true })],
    },
  },
  {
    id: 'tiles.swap.up',
    label: 'Swap tile up',
    description: 'Swap the active tile contents with the tile above',
    category: 'View',
    scope: 'view',
    default: {
      mac: [chord('ArrowUp', { meta: true, alt: true, shift: true })],
      windows: [chord('ArrowUp', { ctrl: true, alt: true, shift: true })],
    },
  },
  {
    id: 'tiles.swap.down',
    label: 'Swap tile down',
    description: 'Swap the active tile contents with the tile below',
    category: 'View',
    scope: 'view',
    default: {
      mac: [chord('ArrowDown', { meta: true, alt: true, shift: true })],
      windows: [chord('ArrowDown', { ctrl: true, alt: true, shift: true })],
    },
  },
  {
    id: 'tiles.swap.last',
    label: 'Swap with last active tile',
    description: 'Swap the active tile contents with the previously active tile',
    category: 'View',
    scope: 'view',
    default: {
      mac: [chord('w', { meta: true, alt: true, shift: true })],
      windows: [chord('w', { ctrl: true, alt: true, shift: true })],
    },
  },
  {
    id: 'tiles.focus.left',
    label: 'Focus tile left',
    description: 'Move focus to the tile to the left',
    category: 'View',
    scope: 'view',
    default: {
      mac: [chord('ArrowLeft', { ctrl: true, alt: true })],
      windows: [chord('ArrowLeft', { ctrl: true, alt: true })],
    },
  },
  {
    id: 'tiles.focus.right',
    label: 'Focus tile right',
    description: 'Move focus to the tile to the right',
    category: 'View',
    scope: 'view',
    default: {
      mac: [chord('ArrowRight', { ctrl: true, alt: true })],
      windows: [chord('ArrowRight', { ctrl: true, alt: true })],
    },
  },
  {
    id: 'tiles.focus.up',
    label: 'Focus tile up',
    description: 'Move focus to the tile above',
    category: 'View',
    scope: 'view',
    default: {
      mac: [chord('ArrowUp', { ctrl: true, alt: true })],
      windows: [chord('ArrowUp', { ctrl: true, alt: true })],
    },
  },
  {
    id: 'tiles.focus.down',
    label: 'Focus tile down',
    description: 'Move focus to the tile below',
    category: 'View',
    scope: 'view',
    default: {
      mac: [chord('ArrowDown', { ctrl: true, alt: true })],
      windows: [chord('ArrowDown', { ctrl: true, alt: true })],
    },
  },
  {
    id: 'tiles.toggle.expand',
    label: 'Toggle tile expand',
    description: 'Expand the active tile or restore it',
    category: 'View',
    scope: 'view',
    default: {
      mac: [chord('Enter', { meta: true, alt: true })],
      windows: [chord('Enter', { ctrl: true, alt: true })],
    },
  },
  {
    id: 'tiles.balance',
    label: 'Balance tile sizes',
    description: 'Equalize the tile sizes in the current layout',
    category: 'View',
    scope: 'view',
    default: {
      mac: [chord('Enter', { meta: true, alt: true, shift: true })],
      windows: [chord('Enter', { ctrl: true, alt: true, shift: true })],
    },
  },
  {
    id: 'tiles.close.active',
    label: 'Close active tile',
    description: 'Close the active tile',
    category: 'View',
    scope: 'view',
    default: {
      mac: [chord('Backspace', { meta: true, alt: true })],
      windows: [chord('Backspace', { ctrl: true, alt: true })],
    },
  },
  {
    id: 'tiles.close.others',
    label: 'Close other tiles',
    description: 'Close all tiles except the active one',
    category: 'View',
    scope: 'view',
    default: {
      mac: [chord('o', { meta: true, alt: true })],
      windows: [chord('o', { ctrl: true, alt: true })],
    },
  },
  {
    id: 'tiles.open.editor',
    label: 'Open editor tile',
    description: 'Open an editor tile for the focused document',
    category: 'View',
    scope: 'view',
    default: {
      mac: [chord('e', { meta: true, alt: true })],
      windows: [chord('e', { ctrl: true, alt: true })],
    },
  },
  {
    id: 'tiles.open.preview',
    label: 'Open preview tile',
    description: 'Open a preview tile for the focused document',
    category: 'View',
    scope: 'view',
    default: {
      mac: [chord('v', { meta: true, alt: true })],
      windows: [chord('v', { ctrl: true, alt: true })],
    },
  },
  {
    id: 'editor.sync-scroll.toggle',
    label: 'Toggle scroll sync',
    description: 'Lock or unlock preview scrolling with the editor',
    category: 'Editor',
    scope: 'editor',
    default: {
      mac: [chord('s', { meta: true, alt: true, shift: true })],
      windows: [chord('s', { ctrl: true, alt: true, shift: true })],
    },
  },
  {
    id: 'editor.vim.toggle',
    label: 'Toggle Vim mode',
    description: 'Enable or disable Vim keybindings',
    category: 'Editor',
    scope: 'editor',
    default: {
      mac: [chord('v', { meta: true, alt: true, shift: true })],
      windows: [chord('v', { ctrl: true, alt: true, shift: true })],
    },
  },
  {
    id: 'editor.upload.trigger',
    label: 'Insert file…',
    description: 'Open the file picker to upload attachments',
    category: 'Editor',
    scope: 'editor',
    default: {
      mac: [chord('u', { meta: true, alt: true, shift: true })],
      windows: [chord('u', { ctrl: true, alt: true, shift: true })],
    },
  },
]

export const findShortcut = (id: string) => SHORTCUT_ACTIONS.find((action) => action.id === id)
