export const toneVarDefaults = [
  "[--tone-border:var(--tone-default-border)]",
  "[--tone-bg:var(--tone-default-bg)]",
  "[--tone-body:var(--tone-default-body)]",
  "[--tone-title:var(--tone-default-title)]",
  "[--tone-description:var(--tone-default-description)]",
  "[--tone-bar:var(--tone-default-bar)]",
  "[--tone-gradient:var(--tone-default-gradient)]",
  "[--tone-icon-border:var(--tone-default-icon-border)]",
  "[--tone-icon-bg:var(--tone-default-icon-bg)]",
  "[--tone-icon-fg:var(--tone-default-icon-fg)]",
  "bg-[color:var(--tone-bg)]",
].join(" ")

export const toneVarOverrides = {
  default: "",
  info: [
    "[--tone-border:var(--tone-info-border)]",
    "[--tone-bg:var(--tone-info-bg)]",
    "[--tone-body:var(--tone-info-body)]",
    "[--tone-title:var(--tone-info-title)]",
    "[--tone-description:var(--tone-info-description)]",
    "[--tone-bar:var(--tone-info-bar)]",
    "[--tone-gradient:var(--tone-info-gradient)]",
    "[--tone-icon-border:var(--tone-info-icon-border)]",
    "[--tone-icon-bg:var(--tone-info-icon-bg)]",
    "[--tone-icon-fg:var(--tone-info-icon-fg)]",
  ].join(" "),
  success: [
    "[--tone-border:var(--tone-success-border)]",
    "[--tone-bg:var(--tone-success-bg)]",
    "[--tone-body:var(--tone-success-body)]",
    "[--tone-title:var(--tone-success-title)]",
    "[--tone-description:var(--tone-success-description)]",
    "[--tone-bar:var(--tone-success-bar)]",
    "[--tone-gradient:var(--tone-success-gradient)]",
    "[--tone-icon-border:var(--tone-success-icon-border)]",
    "[--tone-icon-bg:var(--tone-success-icon-bg)]",
    "[--tone-icon-fg:var(--tone-success-icon-fg)]",
  ].join(" "),
  warning: [
    "[--tone-border:var(--tone-warning-border)]",
    "[--tone-bg:var(--tone-warning-bg)]",
    "[--tone-body:var(--tone-warning-body)]",
    "[--tone-title:var(--tone-warning-title)]",
    "[--tone-description:var(--tone-warning-description)]",
    "[--tone-bar:var(--tone-warning-bar)]",
    "[--tone-gradient:var(--tone-warning-gradient)]",
    "[--tone-icon-border:var(--tone-warning-icon-border)]",
    "[--tone-icon-bg:var(--tone-warning-icon-bg)]",
    "[--tone-icon-fg:var(--tone-warning-icon-fg)]",
  ].join(" "),
  destructive: [
    "[--tone-border:var(--tone-destructive-border)]",
    "[--tone-bg:var(--tone-destructive-bg)]",
    "[--tone-body:var(--tone-destructive-body)]",
    "[--tone-title:var(--tone-destructive-title)]",
    "[--tone-description:var(--tone-destructive-description)]",
    "[--tone-bar:var(--tone-destructive-bar)]",
    "[--tone-gradient:var(--tone-destructive-gradient)]",
    "[--tone-icon-border:var(--tone-destructive-icon-border)]",
    "[--tone-icon-bg:var(--tone-destructive-icon-bg)]",
    "[--tone-icon-fg:var(--tone-destructive-icon-fg)]",
  ].join(" "),
} as const
