import Config

dev_port = String.to_integer(System.get_env("PORT") || "4000")
secret_key_base = "oCPZPJlBPGtaKBilrRvqy6+nknJNajIhmtJTTMJYq8DxuNPnWN3xvwrYXNuUAKu2"

# Configure your database
config :refmd, RefMD.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "refmd_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :refmd, RefMDWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  url: [host: "localhost", port: dev_port, scheme: "http"],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: secret_key_base,
  watchers: []

config :refmd, token_secret_key_base: secret_key_base

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Dummy salt secret for consistent fake salts (non-existent users)
config :refmd, dummy_salt_secret: "dev-dummy-salt-secret-do-not-use-in-production"
config :refmd, e2e_rate_limit_bypass: true

config :refmd,
  share_server_key_id: "dev-share-key",
  share_server_keys: %{
    "dev-share-key" => Base.url_encode64(:binary.copy(<<2>>, 32), padding: false)
  }

# CORS origins for VerifyOrigin plug (same-origin in dev)
config :refmd,
  cors_origins:
    Enum.uniq(["http://localhost:#{dev_port}", "http://localhost:4000", "http://localhost:5173"])

# Enable dev routes for dashboard and mailbox
config :refmd, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
