/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OgVariantDotpngRouteImport } from './routes/og/$variant[.]png'
import { Route as appWorkspacesRouteImport } from './routes/(app)/workspaces'
import { Route as appTemporaryRouteImport } from './routes/(app)/temporary'
import { Route as appProfileRouteImport } from './routes/(app)/profile'
import { Route as appDashboardRouteImport } from './routes/(app)/dashboard'
import { Route as appSettingsIndexRouteImport } from './routes/(app)/settings/index'
import { Route as shareShareTokenRouteImport } from './routes/(share)/share/$token'
import { Route as authAuthUnlockRouteImport } from './routes/(auth)/auth/unlock'
import { Route as authAuthSignupRouteImport } from './routes/(auth)/auth/signup'
import { Route as authAuthSigninRouteImport } from './routes/(auth)/auth/signin'
import { Route as authAuthSetupRouteImport } from './routes/(auth)/auth/setup'
import { Route as appTemporaryIdRouteImport } from './routes/(app)/temporary/$id'
import { Route as appSettingsVisibilityRouteImport } from './routes/(app)/settings/visibility'
import { Route as appSettingsShortcutsRouteImport } from './routes/(app)/settings/shortcuts'
import { Route as appSettingsPluginsRouteImport } from './routes/(app)/settings/plugins'
import { Route as appSettingsGitSyncRouteImport } from './routes/(app)/settings/git-sync'
import { Route as appDocumentIdRouteImport } from './routes/(app)/document/$id'
import { Route as publicWSlugIndexRouteImport } from './routes/(public)/w/$slug/index'
import { Route as publicUNameIndexRouteImport } from './routes/(public)/u/$name/index'
import { Route as publicWSlugIdRouteImport } from './routes/(public)/w/$slug/$id'
import { Route as publicUNameIdRouteImport } from './routes/(public)/u/$name/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OgVariantDotpngRoute = OgVariantDotpngRouteImport.update({
  id: '/og/$variant.png',
  path: '/og/$variant.png',
  getParentRoute: () => rootRouteImport,
} as any)
const appWorkspacesRoute = appWorkspacesRouteImport.update({
  id: '/(app)/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const appTemporaryRoute = appTemporaryRouteImport.update({
  id: '/(app)/temporary',
  path: '/temporary',
  getParentRoute: () => rootRouteImport,
} as any)
const appProfileRoute = appProfileRouteImport.update({
  id: '/(app)/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const appDashboardRoute = appDashboardRouteImport.update({
  id: '/(app)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const appSettingsIndexRoute = appSettingsIndexRouteImport.update({
  id: '/(app)/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const shareShareTokenRoute = shareShareTokenRouteImport.update({
  id: '/(share)/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthUnlockRoute = authAuthUnlockRouteImport.update({
  id: '/(auth)/auth/unlock',
  path: '/auth/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthSignupRoute = authAuthSignupRouteImport.update({
  id: '/(auth)/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthSigninRoute = authAuthSigninRouteImport.update({
  id: '/(auth)/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthSetupRoute = authAuthSetupRouteImport.update({
  id: '/(auth)/auth/setup',
  path: '/auth/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const appTemporaryIdRoute = appTemporaryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => appTemporaryRoute,
} as any)
const appSettingsVisibilityRoute = appSettingsVisibilityRouteImport.update({
  id: '/(app)/settings/visibility',
  path: '/settings/visibility',
  getParentRoute: () => rootRouteImport,
} as any)
const appSettingsShortcutsRoute = appSettingsShortcutsRouteImport.update({
  id: '/(app)/settings/shortcuts',
  path: '/settings/shortcuts',
  getParentRoute: () => rootRouteImport,
} as any)
const appSettingsPluginsRoute = appSettingsPluginsRouteImport.update({
  id: '/(app)/settings/plugins',
  path: '/settings/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const appSettingsGitSyncRoute = appSettingsGitSyncRouteImport.update({
  id: '/(app)/settings/git-sync',
  path: '/settings/git-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const appDocumentIdRoute = appDocumentIdRouteImport.update({
  id: '/(app)/document/$id',
  path: '/document/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const publicWSlugIndexRoute = publicWSlugIndexRouteImport.update({
  id: '/(public)/w/$slug/',
  path: '/w/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicUNameIndexRoute = publicUNameIndexRouteImport.update({
  id: '/(public)/u/$name/',
  path: '/u/$name/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicWSlugIdRoute = publicWSlugIdRouteImport.update({
  id: '/(public)/w/$slug/$id',
  path: '/w/$slug/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const publicUNameIdRoute = publicUNameIdRouteImport.update({
  id: '/(public)/u/$name/$id',
  path: '/u/$name/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof appDashboardRoute
  '/profile': typeof appProfileRoute
  '/temporary': typeof appTemporaryRouteWithChildren
  '/workspaces': typeof appWorkspacesRoute
  '/og/$variant.png': typeof OgVariantDotpngRoute
  '/document/$id': typeof appDocumentIdRoute
  '/settings/git-sync': typeof appSettingsGitSyncRoute
  '/settings/plugins': typeof appSettingsPluginsRoute
  '/settings/shortcuts': typeof appSettingsShortcutsRoute
  '/settings/visibility': typeof appSettingsVisibilityRoute
  '/temporary/$id': typeof appTemporaryIdRoute
  '/auth/setup': typeof authAuthSetupRoute
  '/auth/signin': typeof authAuthSigninRoute
  '/auth/signup': typeof authAuthSignupRoute
  '/auth/unlock': typeof authAuthUnlockRoute
  '/share/$token': typeof shareShareTokenRoute
  '/settings': typeof appSettingsIndexRoute
  '/u/$name/$id': typeof publicUNameIdRoute
  '/w/$slug/$id': typeof publicWSlugIdRoute
  '/u/$name': typeof publicUNameIndexRoute
  '/w/$slug': typeof publicWSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof appDashboardRoute
  '/profile': typeof appProfileRoute
  '/temporary': typeof appTemporaryRouteWithChildren
  '/workspaces': typeof appWorkspacesRoute
  '/og/$variant.png': typeof OgVariantDotpngRoute
  '/document/$id': typeof appDocumentIdRoute
  '/settings/git-sync': typeof appSettingsGitSyncRoute
  '/settings/plugins': typeof appSettingsPluginsRoute
  '/settings/shortcuts': typeof appSettingsShortcutsRoute
  '/settings/visibility': typeof appSettingsVisibilityRoute
  '/temporary/$id': typeof appTemporaryIdRoute
  '/auth/setup': typeof authAuthSetupRoute
  '/auth/signin': typeof authAuthSigninRoute
  '/auth/signup': typeof authAuthSignupRoute
  '/auth/unlock': typeof authAuthUnlockRoute
  '/share/$token': typeof shareShareTokenRoute
  '/settings': typeof appSettingsIndexRoute
  '/u/$name/$id': typeof publicUNameIdRoute
  '/w/$slug/$id': typeof publicWSlugIdRoute
  '/u/$name': typeof publicUNameIndexRoute
  '/w/$slug': typeof publicWSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)/dashboard': typeof appDashboardRoute
  '/(app)/profile': typeof appProfileRoute
  '/(app)/temporary': typeof appTemporaryRouteWithChildren
  '/(app)/workspaces': typeof appWorkspacesRoute
  '/og/$variant.png': typeof OgVariantDotpngRoute
  '/(app)/document/$id': typeof appDocumentIdRoute
  '/(app)/settings/git-sync': typeof appSettingsGitSyncRoute
  '/(app)/settings/plugins': typeof appSettingsPluginsRoute
  '/(app)/settings/shortcuts': typeof appSettingsShortcutsRoute
  '/(app)/settings/visibility': typeof appSettingsVisibilityRoute
  '/(app)/temporary/$id': typeof appTemporaryIdRoute
  '/(auth)/auth/setup': typeof authAuthSetupRoute
  '/(auth)/auth/signin': typeof authAuthSigninRoute
  '/(auth)/auth/signup': typeof authAuthSignupRoute
  '/(auth)/auth/unlock': typeof authAuthUnlockRoute
  '/(share)/share/$token': typeof shareShareTokenRoute
  '/(app)/settings/': typeof appSettingsIndexRoute
  '/(public)/u/$name/$id': typeof publicUNameIdRoute
  '/(public)/w/$slug/$id': typeof publicWSlugIdRoute
  '/(public)/u/$name/': typeof publicUNameIndexRoute
  '/(public)/w/$slug/': typeof publicWSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/profile'
    | '/temporary'
    | '/workspaces'
    | '/og/$variant.png'
    | '/document/$id'
    | '/settings/git-sync'
    | '/settings/plugins'
    | '/settings/shortcuts'
    | '/settings/visibility'
    | '/temporary/$id'
    | '/auth/setup'
    | '/auth/signin'
    | '/auth/signup'
    | '/auth/unlock'
    | '/share/$token'
    | '/settings'
    | '/u/$name/$id'
    | '/w/$slug/$id'
    | '/u/$name'
    | '/w/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/profile'
    | '/temporary'
    | '/workspaces'
    | '/og/$variant.png'
    | '/document/$id'
    | '/settings/git-sync'
    | '/settings/plugins'
    | '/settings/shortcuts'
    | '/settings/visibility'
    | '/temporary/$id'
    | '/auth/setup'
    | '/auth/signin'
    | '/auth/signup'
    | '/auth/unlock'
    | '/share/$token'
    | '/settings'
    | '/u/$name/$id'
    | '/w/$slug/$id'
    | '/u/$name'
    | '/w/$slug'
  id:
    | '__root__'
    | '/'
    | '/(app)/dashboard'
    | '/(app)/profile'
    | '/(app)/temporary'
    | '/(app)/workspaces'
    | '/og/$variant.png'
    | '/(app)/document/$id'
    | '/(app)/settings/git-sync'
    | '/(app)/settings/plugins'
    | '/(app)/settings/shortcuts'
    | '/(app)/settings/visibility'
    | '/(app)/temporary/$id'
    | '/(auth)/auth/setup'
    | '/(auth)/auth/signin'
    | '/(auth)/auth/signup'
    | '/(auth)/auth/unlock'
    | '/(share)/share/$token'
    | '/(app)/settings/'
    | '/(public)/u/$name/$id'
    | '/(public)/w/$slug/$id'
    | '/(public)/u/$name/'
    | '/(public)/w/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appDashboardRoute: typeof appDashboardRoute
  appProfileRoute: typeof appProfileRoute
  appTemporaryRoute: typeof appTemporaryRouteWithChildren
  appWorkspacesRoute: typeof appWorkspacesRoute
  OgVariantDotpngRoute: typeof OgVariantDotpngRoute
  appDocumentIdRoute: typeof appDocumentIdRoute
  appSettingsGitSyncRoute: typeof appSettingsGitSyncRoute
  appSettingsPluginsRoute: typeof appSettingsPluginsRoute
  appSettingsShortcutsRoute: typeof appSettingsShortcutsRoute
  appSettingsVisibilityRoute: typeof appSettingsVisibilityRoute
  authAuthSetupRoute: typeof authAuthSetupRoute
  authAuthSigninRoute: typeof authAuthSigninRoute
  authAuthSignupRoute: typeof authAuthSignupRoute
  authAuthUnlockRoute: typeof authAuthUnlockRoute
  shareShareTokenRoute: typeof shareShareTokenRoute
  appSettingsIndexRoute: typeof appSettingsIndexRoute
  publicUNameIdRoute: typeof publicUNameIdRoute
  publicWSlugIdRoute: typeof publicWSlugIdRoute
  publicUNameIndexRoute: typeof publicUNameIndexRoute
  publicWSlugIndexRoute: typeof publicWSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/$variant.png': {
      id: '/og/$variant.png'
      path: '/og/$variant.png'
      fullPath: '/og/$variant.png'
      preLoaderRoute: typeof OgVariantDotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/workspaces': {
      id: '/(app)/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof appWorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/temporary': {
      id: '/(app)/temporary'
      path: '/temporary'
      fullPath: '/temporary'
      preLoaderRoute: typeof appTemporaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/profile': {
      id: '/(app)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof appProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/dashboard': {
      id: '/(app)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/settings/': {
      id: '/(app)/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof appSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(share)/share/$token': {
      id: '/(share)/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof shareShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/auth/unlock': {
      id: '/(auth)/auth/unlock'
      path: '/auth/unlock'
      fullPath: '/auth/unlock'
      preLoaderRoute: typeof authAuthUnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/auth/signup': {
      id: '/(auth)/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof authAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/auth/signin': {
      id: '/(auth)/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof authAuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/auth/setup': {
      id: '/(auth)/auth/setup'
      path: '/auth/setup'
      fullPath: '/auth/setup'
      preLoaderRoute: typeof authAuthSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/temporary/$id': {
      id: '/(app)/temporary/$id'
      path: '/$id'
      fullPath: '/temporary/$id'
      preLoaderRoute: typeof appTemporaryIdRouteImport
      parentRoute: typeof appTemporaryRoute
    }
    '/(app)/settings/visibility': {
      id: '/(app)/settings/visibility'
      path: '/settings/visibility'
      fullPath: '/settings/visibility'
      preLoaderRoute: typeof appSettingsVisibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/settings/shortcuts': {
      id: '/(app)/settings/shortcuts'
      path: '/settings/shortcuts'
      fullPath: '/settings/shortcuts'
      preLoaderRoute: typeof appSettingsShortcutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/settings/plugins': {
      id: '/(app)/settings/plugins'
      path: '/settings/plugins'
      fullPath: '/settings/plugins'
      preLoaderRoute: typeof appSettingsPluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/settings/git-sync': {
      id: '/(app)/settings/git-sync'
      path: '/settings/git-sync'
      fullPath: '/settings/git-sync'
      preLoaderRoute: typeof appSettingsGitSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/document/$id': {
      id: '/(app)/document/$id'
      path: '/document/$id'
      fullPath: '/document/$id'
      preLoaderRoute: typeof appDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/w/$slug/': {
      id: '/(public)/w/$slug/'
      path: '/w/$slug'
      fullPath: '/w/$slug'
      preLoaderRoute: typeof publicWSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/u/$name/': {
      id: '/(public)/u/$name/'
      path: '/u/$name'
      fullPath: '/u/$name'
      preLoaderRoute: typeof publicUNameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/w/$slug/$id': {
      id: '/(public)/w/$slug/$id'
      path: '/w/$slug/$id'
      fullPath: '/w/$slug/$id'
      preLoaderRoute: typeof publicWSlugIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/u/$name/$id': {
      id: '/(public)/u/$name/$id'
      path: '/u/$name/$id'
      fullPath: '/u/$name/$id'
      preLoaderRoute: typeof publicUNameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface appTemporaryRouteChildren {
  appTemporaryIdRoute: typeof appTemporaryIdRoute
}

const appTemporaryRouteChildren: appTemporaryRouteChildren = {
  appTemporaryIdRoute: appTemporaryIdRoute,
}

const appTemporaryRouteWithChildren = appTemporaryRoute._addFileChildren(
  appTemporaryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appDashboardRoute: appDashboardRoute,
  appProfileRoute: appProfileRoute,
  appTemporaryRoute: appTemporaryRouteWithChildren,
  appWorkspacesRoute: appWorkspacesRoute,
  OgVariantDotpngRoute: OgVariantDotpngRoute,
  appDocumentIdRoute: appDocumentIdRoute,
  appSettingsGitSyncRoute: appSettingsGitSyncRoute,
  appSettingsPluginsRoute: appSettingsPluginsRoute,
  appSettingsShortcutsRoute: appSettingsShortcutsRoute,
  appSettingsVisibilityRoute: appSettingsVisibilityRoute,
  authAuthSetupRoute: authAuthSetupRoute,
  authAuthSigninRoute: authAuthSigninRoute,
  authAuthSignupRoute: authAuthSignupRoute,
  authAuthUnlockRoute: authAuthUnlockRoute,
  shareShareTokenRoute: shareShareTokenRoute,
  appSettingsIndexRoute: appSettingsIndexRoute,
  publicUNameIdRoute: publicUNameIdRoute,
  publicWSlugIdRoute: publicWSlugIdRoute,
  publicUNameIndexRoute: publicUNameIndexRoute,
  publicWSlugIndexRoute: publicWSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
