use contracts::core::dtos::{TextDiffLine, TextDiffLineType, TextDiffResult};
use utoipa::OpenApi;

use crate::http::core::{health, storage_ingest};
// use crate::http::core::markdown; // Removed: E2EE requires client-side rendering
use crate::http::documents::files;
use crate::http::documents::keys as document_keys;
use crate::http::documents::{publishing as public, sharing as shares, tagging as tags};
use crate::http::identity::{api_tokens, auth, keys, migration, shortcuts};
use crate::http::{documents, git, plugins, workspaces};
use crate::ws;

#[derive(OpenApi)]
#[openapi(
    paths(
        auth::openapi::register,
        auth::openapi::login,
        auth::openapi::oauth_state,
        auth::openapi::oauth_login,
        auth::openapi::list_oauth_providers,
        auth::openapi::refresh_session,
        auth::openapi::logout,
        auth::openapi::me,
        auth::openapi::list_sessions,
        auth::openapi::revoke_session,
        api_tokens::openapi::list_api_tokens,
        api_tokens::openapi::create_api_token,
        api_tokens::openapi::revoke_api_token,
        shortcuts::openapi::get_user_shortcuts,
        shortcuts::openapi::update_user_shortcuts,
        keys::openapi::register_public_key,
        keys::openapi::get_my_public_key,
        keys::openapi::get_user_public_key,
        keys::openapi::store_master_key_backup,
        keys::openapi::get_master_key_backup,
        keys::openapi::store_encrypted_private_key,
        keys::openapi::get_encrypted_private_key,
        keys::openapi::mark_e2ee_setup_complete,
        keys::openapi::get_e2ee_status,
        migration::openapi::migrate_to_e2ee,
        migration::openapi::needs_migration,
        document_keys::openapi::get_document_key,
        document_keys::openapi::store_document_key,
        document_keys::openapi::rotate_document_key,
        document_keys::openapi::get_share_key,
        document_keys::openapi::get_share_salt,
        document_keys::openapi::store_share_key,
        document_keys::openapi::store_password_protected_share_key,
        auth::openapi::delete_account,
        ws::documents::yjs::openapi::axum_ws_entry,
        tags::openapi::list_tags,
        tags::openapi::get_document_tags,
        tags::openapi::update_document_tags,
        documents::openapi::list_documents,
        documents::openapi::create_document,
        documents::openapi::get_document,
        documents::openapi::update_document,
        documents::openapi::duplicate_document,
        documents::openapi::delete_document,
        documents::openapi::get_document_content,
        documents::openapi::update_document_content,
        documents::openapi::patch_document_content,
        documents::openapi::archive_document,
        documents::openapi::unarchive_document,
        documents::openapi::download_document,
        documents::openapi::list_document_snapshots,
        documents::openapi::get_document_snapshot,
        documents::openapi::get_document_snapshot_diff,
        documents::openapi::restore_document_snapshot,
        documents::openapi::download_document_snapshot,
        documents::openapi::get_backlinks,
        documents::openapi::get_outgoing_links,
        files::openapi::upload_file,
        files::openapi::get_file,
        files::openapi::list_files,
        shares::openapi::create_share,
        shares::openapi::delete_share,
        shares::openapi::list_document_shares,
        shares::openapi::validate_share_token,
        shares::openapi::get_share_salt,
        shares::openapi::browse_share,
        shares::openapi::list_active_shares,
        shares::openapi::create_share_mount,
        shares::openapi::list_share_mounts,
        shares::openapi::delete_share_mount,
        shares::openapi::list_applicable_shares,
        shares::openapi::materialize_folder_share,
        public::openapi::publish_document,
        public::openapi::unpublish_document,
        public::openapi::get_publish_status,
        public::openapi::list_workspace_public_documents,
        public::openapi::get_public_by_workspace_and_id,
        public::openapi::get_public_content_by_workspace_and_id,
        git::openapi::get_config,
        git::openapi::create_or_update_config,
        git::openapi::delete_config,
        storage_ingest::openapi::enqueue_ingest_events,
        // markdown::openapi::render_markdown, // Removed: E2EE requires client-side rendering
        // markdown::openapi::render_markdown_many, // Removed: E2EE requires client-side rendering
        plugins::openapi::get_manifest,
        // plugins::openapi::exec_action, // Removed: E2EE requires client-side WASM execution
        plugins::openapi::list_records,
        plugins::openapi::create_record,
        plugins::openapi::update_record,
        plugins::openapi::delete_record,
        plugins::openapi::get_kv_value,
        plugins::openapi::put_kv_value,
        plugins::openapi::install_from_url,
        plugins::openapi::uninstall,
        plugins::openapi::sse_updates,
        plugins::openapi::get_plugin_asset,
        workspaces::openapi::list_workspaces,
        workspaces::openapi::create_workspace,
        workspaces::openapi::get_workspace_detail,
        workspaces::openapi::update_workspace,
        workspaces::openapi::delete_workspace,
        workspaces::openapi::leave_workspace,
        workspaces::openapi::switch_workspace,
        workspaces::openapi::list_members,
        workspaces::openapi::update_member_role,
        workspaces::openapi::remove_member,
        workspaces::openapi::get_workspace_permissions,
        workspaces::openapi::list_roles,
        workspaces::openapi::create_role,
        workspaces::openapi::update_role,
        workspaces::openapi::delete_role,
        workspaces::openapi::list_invitations,
        workspaces::openapi::create_invitation,
        workspaces::openapi::revoke_invitation,
        workspaces::openapi::update_invitation_kek,
        workspaces::openapi::accept_invitation,
        workspaces::openapi::download_workspace_archive,
        workspaces::openapi::get_my_workspace_key,
        workspaces::openapi::store_workspace_key,
        workspaces::openapi::list_workspace_keys,
        workspaces::openapi::get_workspace_key_version,
        workspaces::openapi::delete_key_version,
        workspaces::openapi::rotate_workspace_key,
        health::openapi::health,
    ),
    components(schemas(
        auth::RegisterRequest,
        auth::LoginRequest,
        auth::LoginResponse,
        auth::OAuthLoginRequest,
        auth::OAuthStateResponse,
        auth::AuthProvidersResponse,
        auth::AuthProviderInfoResponse,
        auth::UserResponse,
        auth::WorkspaceMembershipResponse,
        auth::SessionResponse,
        auth::RefreshResponse,
        api_tokens::ApiTokenItem,
        api_tokens::ApiTokenCreateRequest,
        api_tokens::ApiTokenCreateResponse,
        shortcuts::UserShortcutResponse,
        shortcuts::UpdateUserShortcutRequest,
        keys::UserPublicKeyResponse,
        keys::RegisterPublicKeyRequest,
        keys::MasterKeyBackupResponse,
        keys::StoreMasterKeyBackupRequest,
        keys::KdfParamsResponse,
        keys::EncryptedPrivateKeyResponse,
        keys::StoreEncryptedPrivateKeyRequest,
        keys::E2eeStatusResponse,
        migration::MigrateRequest,
        migration::MemberEncryptedKekRequest,
        migration::EncryptedDekRequest,
        migration::MigrationResponse,
        migration::NeedsMigrationResponse,
        document_keys::DocumentKeyResponse,
        document_keys::StoreDocumentKeyRequest,
        document_keys::RotateDocumentKeyRequest,
        document_keys::RotateDocumentKeyResponse,
        document_keys::ShareKeyResponse,
        document_keys::ShareSaltResponse,
        document_keys::StoreShareKeyRequest,
        document_keys::StorePasswordProtectedShareKeyRequest,
        document_keys::KdfParamsResponse,
        tags::TagEntry,
        tags::ListTagsResponse,
        tags::DocumentTagEntry,
        tags::DocumentTagsResponse,
        tags::EncryptedTagInput,
        tags::UpdateDocumentTagsRequest,
        documents::Document,
        documents::DocumentListResponse,
        documents::CreateDocumentRequest,
        documents::CreateDocumentDekPayload,
        documents::UpdateDocumentRequest,
        documents::DuplicateDocumentRequest,
        documents::GetContentResponse,
        documents::EncryptedUpdateEntry,
        documents::UpdateDocumentContentRequest,
        documents::DocumentPatchOperationRequest,
        documents::PatchDocumentContentRequest,
        documents::BacklinkInfo,
        documents::BacklinksResponse,
        documents::OutgoingLink,
        documents::OutgoingLinksResponse,
        documents::DocumentDownloadBinary,
        documents::DocumentArchiveBinary,
        documents::DownloadFormat,
        documents::DownloadDocumentQuery,
        documents::SnapshotSummary,
        documents::SnapshotListResponse,
        documents::SnapshotDiffKind,
        documents::SnapshotDiffSideResponse,
        documents::SnapshotDiffResponse,
        documents::SnapshotDiffBaseParam,
        documents::SnapshotRestoreResponse,
        TextDiffResult,
        TextDiffLine,
        TextDiffLineType,
        documents::SnapshotDetailResponse,
        files::UploadFileResponse,
        files::UploadFileMultipart,
        files::ListFileResponse,
        shares::CreateShareRequest,
        shares::CreateShareResponse,
        shares::CreateShareMountRequest,
        shares::ShareItem,
        shares::ShareDocumentResponse,
        shares::ShareSaltResponse,
        shares::ShareBrowseTreeItem,
        shares::ShareBrowseResponse,
        shares::ApplicableShareItem,
        shares::ActiveShareItem,
        shares::ShareMountItem,
        shares::MaterializeResponse,
        public::PublishRequest,
        public::PublishResponse,
        public::PublicDocumentSummary,
        git::GitConfigResponse,
        git::GitRemoteCheckResponse,
        git::CreateGitConfigRequest,
        // markdown::RenderOptionsPayload, // Removed: E2EE requires client-side rendering
        // markdown::PlaceholderItemPayload, // Removed: E2EE requires client-side rendering
        // markdown::RenderResponseBody, // Removed: E2EE requires client-side rendering
        // markdown::RenderRequest, // Removed: E2EE requires client-side rendering
        // markdown::RenderManyRequest, // Removed: E2EE requires client-side rendering
        // markdown::RenderManyResponse, // Removed: E2EE requires client-side rendering
        plugins::ManifestItem,
        plugins::RecordsResponse,
        plugins::CreateRecordBody,
        plugins::UpdateRecordBody,
        plugins::KvValueResponse,
        plugins::KvValueBody,
        // plugins::ExecBody, // Removed: E2EE requires client-side WASM execution
        // plugins::ExecResultResponse, // Removed: E2EE requires client-side WASM execution
        plugins::InstallFromUrlBody,
        plugins::InstallResponse,
        plugins::UninstallBody,
        workspaces::WorkspaceResponse,
        workspaces::CreateWorkspaceRequest,
        workspaces::WorkspaceMemberResponse,
        workspaces::UpdateMemberRoleRequest,
        workspaces::UpdateWorkspaceRequest,
        workspaces::WorkspaceRoleResponse,
        workspaces::PermissionOverridePayload,
        workspaces::CreateWorkspaceRoleRequest,
        workspaces::UpdateWorkspaceRoleRequest,
        workspaces::SwitchWorkspaceResponse,
        workspaces::WorkspacePermissionsResponse,
        workspaces::WorkspaceInvitationResponse,
        workspaces::CreateWorkspaceInvitationRequest,
        workspaces::AcceptInvitationResponse,
        workspaces::UpdateInvitationKekRequest,
        workspaces::DownloadWorkspaceQuery,
        workspaces::WorkspaceKeyResponse,
        workspaces::StoreWorkspaceKeyRequest,
        workspaces::WorkspaceKeyVersionResponse,
        workspaces::DeleteKeyVersionResponse,
        workspaces::RotationMemberKey,
        workspaces::RotateWorkspaceKeyRequest,
        workspaces::RotateWorkspaceKeyResponse,
        storage_ingest::IngestBatchRequest,
        storage_ingest::IngestEventRequest,
        storage_ingest::IngestKindParam,
        health::HealthResp,
    )),
    tags(
        (name = "Auth", description = "Authentication"),
        (name = "E2EE", description = "End-to-end encryption key management"),
        (name = "Documents", description = "Documents management"),
        (name = "Files", description = "File management"),
        (name = "Sharing", description = "Document sharing"),
        (name = "Public Documents", description = "Public pages"),
        (name = "Realtime", description = "Yjs WebSocket endpoint (/yjs/:id)"),
        (name = "Git", description = "Git config storage (git operations are client-side)"),
        (name = "Markdown", description = "Markdown rendering"),
        (name = "Plugins", description = "Plugins management & data APIs"),
        (name = "Storage", description = "Storage ingest APIs"),
        (name = "Health", description = "System health checks")
    )
)]
pub struct ApiDoc;
