/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/kdf-migration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Migrate KDF parameters */
        post: operations["RefMDWeb.AuthController.kdf_migration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login with credentials */
        post: operations["RefMDWeb.AuthController.login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current session info */
        get: operations["RefMDWeb.AuthController.me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: operations["RefMDWeb.AuthController.register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/salt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get salt for email */
        get: operations["RefMDWeb.AuthController.salt"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Logout current session */
        delete: operations["RefMDWeb.AuthController.logout"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a pending device */
        post: operations["RefMDWeb.DeviceController.create_pending"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/pending/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve a pending device */
        post: operations["RefMDWeb.DeviceController.approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/encryption/setup-complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark encryption setup as complete */
        post: operations["RefMDWeb.EncryptionController.setup_complete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/encryption/workspaces/{workspace_id}/kek-backup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get active KEK backup */
        get: operations["RefMDWeb.EncryptionController.get_kek_backup"];
        put?: never;
        /** Create a KEK backup */
        post: operations["RefMDWeb.EncryptionController.create_kek_backup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/encryption/workspaces/{workspace_id}/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get workspace encryption keys */
        get: operations["RefMDWeb.EncryptionController.get_workspace_keys"];
        put?: never;
        /** Create a workspace encryption key */
        post: operations["RefMDWeb.EncryptionController.create_workspace_key"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApproveDeviceRequest */
        ApproveDeviceRequest: {
            identity_signature: string;
        };
        /** ApproveDeviceResponse */
        ApproveDeviceResponse: {
            device: components["schemas"]["DeviceInfo"];
        };
        /** CreateKekBackupRequest */
        CreateKekBackupRequest: {
            encrypted_kek: string;
            key_version: number;
            nonce: string;
        };
        /** CreatePendingDeviceRequest */
        CreatePendingDeviceRequest: {
            client_nonce: string;
            device_type: string;
            ecdh_public_key: string;
            name: string;
            signing_public_key: string;
        };
        /** CreatePendingDeviceResponse */
        CreatePendingDeviceResponse: {
            /** Format: uuid */
            id: string;
        };
        /** CreateWorkspaceKeyRequest */
        CreateWorkspaceKeyRequest: {
            /** Format: uuid */
            device_id: string;
            encrypted_kek: string;
            is_active?: boolean;
            key_version: number;
            nonce: string;
            /** Format: uuid */
            sender_device_id: string;
        };
        /** DeviceInfo */
        DeviceInfo: {
            device_type: string;
            /** Format: uuid */
            id: string;
            name: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            details?: {
                [key: string]: unknown;
            };
            error: string;
            step?: string;
        };
        /** KdfMigrationRequest */
        KdfMigrationRequest: {
            new_auth_key: string;
            new_encrypted_umk: string;
            new_kdf_params: components["schemas"]["KdfParams"];
            new_nonce: string;
        };
        /** KdfParams */
        KdfParams: {
            algorithm: string;
            hash_length: number;
            iterations: number;
            memory: number;
            parallelism: number;
        };
        /** KekBackupResponse */
        KekBackupResponse: {
            encrypted_kek: string;
            key_version: number;
            nonce: string;
        };
        /** LoginKeys */
        LoginKeys: {
            encrypted_ecdh_private: string;
            encrypted_ecdh_private_nonce: string;
            encrypted_signing_private: string;
            encrypted_signing_private_nonce: string;
            encrypted_umk?: string;
            umk_nonce?: string;
        } | null;
        /** LoginRequest */
        LoginRequest: {
            auth_key: string;
            /** Format: uuid */
            device_id?: string;
            /** Format: email */
            email: string;
            remember_me?: boolean;
        };
        /** LoginResponse */
        LoginResponse: {
            device_verified: boolean;
            kdf_migration_required?: boolean;
            keys?: components["schemas"]["LoginKeys"];
            /** Format: uuid */
            session_id: string;
            target_kdf_params?: components["schemas"]["KdfParams"];
            user: components["schemas"]["UserInfo"];
        };
        /** MeResponse */
        MeResponse: {
            auth_type?: string | null;
            /** Format: uuid */
            device_id?: string | null;
            device_verified: boolean;
            /** Format: date-time */
            expires_at: string;
            keys?: components["schemas"]["LoginKeys"];
            /** Format: uuid */
            session_id: string;
            user: components["schemas"]["UserInfoWithSetup"];
        };
        /** OkResponse */
        OkResponse: {
            ok: boolean;
        };
        /** RegisterRequest */
        RegisterRequest: {
            auth_key: string;
            ecdh_public_key: string;
            /** Format: email */
            email: string;
            encrypted_ecdh_private: string;
            encrypted_ecdh_private_nonce: string;
            encrypted_signing_private: string;
            encrypted_signing_private_nonce: string;
            encrypted_umk: string;
            kdf_params: components["schemas"]["KdfParams"];
            name: string;
            recovery_encrypted_umk: string;
            recovery_nonce: string;
            salt: string;
            signing_public_key: string;
            umk_nonce: string;
        };
        /** RegisterResponse */
        RegisterResponse: {
            /** Format: uuid */
            session_id: string;
            user: components["schemas"]["UserInfo"];
            /** Format: uuid */
            workspace_id: string;
        };
        /** SaltResponse */
        SaltResponse: {
            kdf_params: components["schemas"]["KdfParams"];
            salt: string;
        };
        /** UserInfo */
        UserInfo: {
            /** Format: email */
            email: string;
            /** Format: uuid */
            id: string;
            name: string;
        };
        /** UserInfoWithSetup */
        UserInfoWithSetup: {
            /** Format: email */
            email: string;
            /** Format: date-time */
            encryption_setup_at?: string | null;
            /** Format: uuid */
            id: string;
            name: string;
        };
        /** WorkspaceKeyItem */
        WorkspaceKeyItem: {
            encrypted_kek: string;
            key_version: number;
            nonce: string;
            /** Format: uuid */
            sender_device_id: string;
        };
        /** WorkspaceKeysResponse */
        WorkspaceKeysResponse: {
            keys: components["schemas"]["WorkspaceKeyItem"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "RefMDWeb.AuthController.kdf_migration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description KDF migration params */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["KdfMigrationRequest"];
            };
        };
        responses: {
            /** @description Migration result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Migration failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "RefMDWeb.AuthController.login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Login params */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "RefMDWeb.AuthController.me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "RefMDWeb.AuthController.register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Registration params */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Registration response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "RefMDWeb.AuthController.salt": {
        parameters: {
            query: {
                email: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Salt response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaltResponse"];
                };
            };
        };
    };
    "RefMDWeb.AuthController.logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logout result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    "RefMDWeb.DeviceController.create_pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Device params */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreatePendingDeviceRequest"];
            };
        };
        responses: {
            /** @description Pending device */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatePendingDeviceResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "RefMDWeb.DeviceController.approve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** @description Approval params */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ApproveDeviceRequest"];
            };
        };
        responses: {
            /** @description Approved device */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApproveDeviceResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Approval failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "RefMDWeb.EncryptionController.setup_complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Setup complete */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    "RefMDWeb.EncryptionController.get_kek_backup": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description KEK backup */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KekBackupResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "RefMDWeb.EncryptionController.create_kek_backup": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        /** @description Backup params */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateKekBackupRequest"];
            };
        };
        responses: {
            /** @description Backup created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Workspace not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Version mismatch */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "RefMDWeb.EncryptionController.get_workspace_keys": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workspace keys */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceKeysResponse"];
                };
            };
        };
    };
    "RefMDWeb.EncryptionController.create_workspace_key": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        /** @description Key params */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateWorkspaceKeyRequest"];
            };
        };
        responses: {
            /** @description Key created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
