/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login with password authentication
         * @description Authenticates a user with email and authKey.
         *     Session token is set via HttpOnly cookie (not in response body).
         *     Client should derive authKey from password using Argon2id + HKDF.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout and clear session
         * @description Clears the session cookie. Client should also clear DSK from IndexedDB.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user info and encrypted keys
         * @description Returns user info and encrypted keys for session restoration.
         *     Requires valid session cookie. Used when client has DSK cached but needs encrypted keys.
         */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new password user
         * @description Creates a new user account with password authentication and E2EE keys.
         *     All encryption is performed client-side; server stores encrypted data only.
         *     Registration is atomic - all entities are created in a single transaction.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/salt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get salt and KDF parameters for login
         * @description Returns the salt and KDF parameters needed to derive the master key.
         *     For unknown users, returns a deterministic dummy salt to prevent user enumeration.
         *     KDF parameters are always the global default settings.
         */
        get: operations["get_salt"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a document */
        get: operations["get_document"];
        put?: never;
        post?: never;
        /** Delete a document (permanent) */
        delete: operations["delete_document"];
        options?: never;
        head?: never;
        /** Update a document */
        patch: operations["update_document"];
        trace?: never;
    };
    "/api/documents/{document_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive a document (read-only) */
        post: operations["archive_document"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/unarchive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unarchive a document */
        post: operations["unarchive_document"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/encryption/documents/{document_id}/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get document key (DEK)
         * @description Retrieves the active DEK for a document.
         *     Requires workspace membership with Read permission.
         */
        get: operations["get_document_key"];
        put?: never;
        /**
         * Save document key (DEK)
         * @description Saves an encrypted DEK for a document.
         *     Requires workspace membership with Write permission.
         */
        post: operations["save_document_key"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/encryption/workspaces/{workspace_id}/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get workspace key (KEK)
         * @description Retrieves the active KEK for the authenticated user's device.
         *     Requires workspace membership with Read permission.
         */
        get: operations["get_workspace_key"];
        put?: never;
        /**
         * Save workspace key (KEK)
         * @description Saves an encrypted KEK for the authenticated user's device.
         *     Requires workspace membership with Read permission.
         */
        post: operations["save_workspace_key"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List user's workspaces
         * @description Returns all workspaces the authenticated user is a member of.
         */
        get: operations["list_workspaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get workspace details
         * @description Returns workspace details with membership info for the authenticated user.
         */
        get: operations["get_workspace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List documents in a workspace */
        get: operations["list_documents"];
        put?: never;
        /** Create a new document */
        post: operations["create_document"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Error response */
        AuthErrorResponse: {
            /**
             * @description Error message
             * @example invalid email
             */
            error: string;
        };
        /** @description Create document request */
        CreateDocumentRequest: {
            encrypted_title?: string | null;
            encrypted_title_nonce?: string | null;
            is_folder?: boolean;
            /** Format: uuid */
            parent_id?: string | null;
            title: string;
        };
        /** @description Document error response */
        DocumentErrorResponse: {
            error: string;
        };
        /** @description Document key response */
        DocumentKeyResponse: {
            /**
             * @description Document ID
             * @example 01234567-89ab-cdef-0123-456789abcdef
             */
            document_id: string;
            /**
             * @description Encrypted DEK (base64url encoded)
             * @example base64url-encoded-encrypted-dek
             */
            encrypted_dek: string;
            /**
             * @description Whether this is the active key
             * @example true
             */
            is_active: boolean;
            /**
             * Format: int32
             * @description Key version
             * @example 1
             */
            key_version: number;
            /**
             * @description Encryption nonce (base64url encoded)
             * @example base64url-encoded-nonce
             */
            nonce: string;
        };
        /** @description Document response */
        DocumentResponse: {
            archived_at?: string | null;
            created_at: string;
            created_by?: string | null;
            doc_type: string;
            encrypted_title?: string | null;
            id: string;
            is_archived: boolean;
            is_encrypted: boolean;
            parent_id?: string | null;
            slug: string;
            title: string;
            updated_at: string;
            workspace_id: string;
        };
        /** @description Error response */
        EncryptionErrorResponse: {
            /**
             * @description Error message
             * @example key not found
             */
            error: string;
        };
        /** @description Get salt query parameters (HTTP) */
        GetSaltQueryParams: {
            /**
             * @description User email address
             * @example user@example.com
             */
            email: string;
        };
        /** @description Get salt response */
        GetSaltResponse: {
            /** @description KDF parameters */
            kdf_params: components["schemas"]["KdfParamsResponse"];
            /**
             * @description KDF type (always "argon2id")
             * @example argon2id
             */
            kdf_type: string;
            /**
             * @description Salt for KDF (base64 encoded, 32 bytes)
             * @example base64-encoded-salt
             */
            salt: string;
        };
        /** @description Get workspace key query params */
        GetWorkspaceKeyParams: {
            /**
             * Format: uuid
             * @description Device ID
             * @example 01234567-89ab-cdef-0123-456789abcdef
             */
            device_id: string;
        };
        /** @description KDF parameters response */
        KdfParamsResponse: {
            /**
             * Format: int32
             * @description Memory cost in KiB
             * @example 65536
             */
            memory_cost: number;
            /**
             * Format: int32
             * @description Parallelism factor
             * @example 4
             */
            parallelism: number;
            /**
             * Format: int32
             * @description Time cost (iterations)
             * @example 3
             */
            time_cost: number;
        };
        /** @description List documents query params */
        ListDocumentsParams: {
            include_archived?: boolean;
            /** Format: uuid */
            parent_id?: string | null;
            root_only?: boolean;
        };
        /** @description List documents response */
        ListDocumentsResponse: {
            documents: components["schemas"]["DocumentResponse"][];
        };
        /** @description List workspaces response */
        ListWorkspacesResponse: {
            /** @description List of workspaces with membership info */
            workspaces: components["schemas"]["WorkspaceWithMembershipResponse"][];
        };
        /** @description Login request */
        LoginRequest: {
            /**
             * @description authKey for authentication (base64url encoded)
             * @example base64url-encoded-auth-key
             */
            auth_key: string;
            /**
             * @description User email address
             * @example user@example.com
             */
            email: string;
            /**
             * @description Remember me flag for extended session duration
             * @example false
             */
            remember_me: boolean;
        };
        /**
         * @description Login response
         *
         *     Session token is set via HttpOnly cookie, not in JSON body.
         */
        LoginResponse: {
            /**
             * @description User email
             * @example user@example.com
             */
            email: string;
            /**
             * @description Encrypted ECDH private key (base64url encoded)
             * @example base64url-encoded-encrypted-ecdh-private
             */
            encrypted_ecdh_private: string;
            /**
             * @description Encrypted ECDH private key nonce (base64url encoded)
             * @example base64url-encoded-nonce
             */
            encrypted_ecdh_private_nonce: string;
            /**
             * @description Encrypted signing private key (base64url encoded)
             * @example base64url-encoded-encrypted-signing-private
             */
            encrypted_signing_private: string;
            /**
             * @description Encrypted signing private key nonce (base64url encoded)
             * @example base64url-encoded-nonce
             */
            encrypted_signing_private_nonce: string;
            /**
             * @description Encrypted UMK (base64url encoded)
             * @example base64url-encoded-encrypted-umk
             */
            encrypted_umk: string;
            /** @description Session expiration timestamp */
            expires_at: string;
            /**
             * @description UMK nonce (base64url encoded)
             * @example base64url-encoded-nonce
             */
            umk_nonce: string;
            /**
             * @description User ID
             * @example 01234567-89ab-cdef-0123-456789abcdef
             */
            user_id: string;
        };
        /** @description Logout response */
        LogoutResponse: {
            /**
             * @description Success message
             * @example logged out
             */
            message: string;
        };
        /** @description Current user response (for session restoration) */
        MeResponse: {
            /**
             * @description Authentication type ("password" or "oauth")
             * @example password
             */
            auth_type: string;
            /**
             * @description User email
             * @example user@example.com
             */
            email: string;
            /**
             * @description Encrypted ECDH private key (base64url encoded)
             * @example base64url-encoded-encrypted-ecdh-private
             */
            encrypted_ecdh_private: string;
            /**
             * @description Encrypted ECDH private key nonce (base64url encoded)
             * @example base64url-encoded-nonce
             */
            encrypted_ecdh_private_nonce: string;
            /**
             * @description Encrypted signing private key (base64url encoded)
             * @example base64url-encoded-encrypted-signing-private
             */
            encrypted_signing_private: string;
            /**
             * @description Encrypted signing private key nonce (base64url encoded)
             * @example base64url-encoded-nonce
             */
            encrypted_signing_private_nonce: string;
            /**
             * @description Encrypted UMK (base64url encoded, null for OAuth users)
             * @example base64url-encoded-encrypted-umk
             */
            encrypted_umk?: string | null;
            /** @description Session expiration timestamp */
            expires_at: string;
            /**
             * @description User display name
             * @example John Doe
             */
            name: string;
            /**
             * @description UMK nonce (base64url encoded, null for OAuth users)
             * @example base64url-encoded-nonce
             */
            umk_nonce?: string | null;
            /**
             * @description User ID
             * @example 01234567-89ab-cdef-0123-456789abcdef
             */
            user_id: string;
        };
        /** @description Workspace membership response */
        MembershipResponse: {
            /** @description Whether this is the user's default workspace */
            is_default: boolean;
            /** @description User's role in the workspace */
            role: components["schemas"]["RoleResponse"];
        };
        /** @description Register password user request */
        RegisterRequest: {
            /**
             * @description authKey for login (base64url encoded)
             * @example base64url-encoded-auth-key
             */
            auth_key: string;
            /**
             * @description ECDH public key (base64url encoded, 32 bytes)
             * @example base64url-encoded-ecdh-public-key
             */
            ecdh_public_key: string;
            /**
             * @description User email address
             * @example user@example.com
             */
            email: string;
            /**
             * @description Encrypted ECDH private key (base64url encoded)
             * @example base64url-encoded-encrypted-ecdh-private
             */
            encrypted_ecdh_private: string;
            /**
             * @description Encrypted ECDH private key nonce (base64url encoded)
             * @example base64url-encoded-nonce
             */
            encrypted_ecdh_private_nonce: string;
            /**
             * @description Encrypted signing private key (base64url encoded)
             * @example base64url-encoded-encrypted-signing-private
             */
            encrypted_signing_private: string;
            /**
             * @description Encrypted signing private key nonce (base64url encoded)
             * @example base64url-encoded-nonce
             */
            encrypted_signing_private_nonce: string;
            /**
             * @description Encrypted UMK (base64url encoded)
             * @example base64url-encoded-encrypted-umk
             */
            encrypted_umk: string;
            /**
             * @description User display name
             * @example John Doe
             */
            name: string;
            /**
             * @description Recovery encrypted UMK (base64url encoded)
             * @example base64url-encoded-recovery-encrypted-umk
             */
            recovery_encrypted_umk: string;
            /**
             * @description Recovery nonce (base64url encoded)
             * @example base64url-encoded-recovery-nonce
             */
            recovery_nonce: string;
            /**
             * @description Salt for KDF (base64url encoded, 32 bytes)
             * @example base64url-encoded-salt
             */
            salt: string;
            /**
             * @description Signing public key (base64url encoded, 32 bytes)
             * @example base64url-encoded-signing-public-key
             */
            signing_public_key: string;
            /**
             * @description UMK nonce (base64url encoded)
             * @example base64url-encoded-nonce
             */
            umk_nonce: string;
            /**
             * Format: uuid
             * @description Client-generated User ID (UUID) - required for AAD binding
             * @example 01234567-89ab-cdef-0123-456789abcdef
             */
            user_id: string;
        };
        /** @description Register response */
        RegisterResponse: {
            /**
             * @description User email address
             * @example user@example.com
             */
            email: string;
            /**
             * @description User ID (UUID)
             * @example 01234567-89ab-cdef-0123-456789abcdef
             */
            id: string;
        };
        /** @description Role response */
        RoleResponse: {
            /**
             * @description Base role type
             * @example owner
             */
            base_role: string;
            /**
             * @description Role ID
             * @example 01234567-89ab-cdef-0123-456789abcdef
             */
            id: string;
            /**
             * @description Role name
             * @example owner
             */
            name: string;
        };
        /** @description Save document key request */
        SaveDocumentKeyRequest: {
            /**
             * @description Encrypted DEK (base64url encoded)
             * @example base64url-encoded-encrypted-dek
             */
            encrypted_dek: string;
            /**
             * @description Whether this is the active key
             * @example true
             */
            is_active: boolean;
            /**
             * Format: int32
             * @description Key version (optional, default: 1)
             * @example 1
             */
            key_version?: number | null;
            /**
             * @description Encryption nonce (base64url encoded)
             * @example base64url-encoded-nonce
             */
            nonce: string;
        };
        /** @description Save workspace key request */
        SaveWorkspaceKeyRequest: {
            /**
             * Format: uuid
             * @description Device ID (client-generated UUID)
             * @example 01234567-89ab-cdef-0123-456789abcdef
             */
            device_id: string;
            /**
             * @description Encrypted KEK (base64url encoded)
             * @example base64url-encoded-encrypted-kek
             */
            encrypted_kek: string;
            /**
             * @description Whether this is the active key
             * @example true
             */
            is_active: boolean;
            /**
             * Format: int32
             * @description Key version (optional, default: 1)
             * @example 1
             */
            key_version?: number | null;
            /**
             * @description Encryption nonce (base64url encoded)
             * @example base64url-encoded-nonce
             */
            nonce: string;
            /**
             * Format: uuid
             * @description Sender device ID (for HKDF info)
             * @example 01234567-89ab-cdef-0123-456789abcdef
             */
            sender_device_id: string;
        };
        /** @description Update document request */
        UpdateDocumentRequest: {
            encrypted_title?: string | null;
            encrypted_title_nonce?: string | null;
            /** Format: uuid */
            parent_id?: string | null;
            title?: string | null;
        };
        /** @description Workspace error response */
        WorkspaceErrorResponse: {
            /**
             * @description Error message
             * @example workspace not found
             */
            error: string;
        };
        /** @description Workspace key response */
        WorkspaceKeyResponse: {
            /**
             * @description Device ID
             * @example 01234567-89ab-cdef-0123-456789abcdef
             */
            device_id: string;
            /**
             * @description Encrypted KEK (base64url encoded)
             * @example base64url-encoded-encrypted-kek
             */
            encrypted_kek: string;
            /**
             * @description Whether this is the active key
             * @example true
             */
            is_active: boolean;
            /**
             * Format: int32
             * @description Key version
             * @example 1
             */
            key_version: number;
            /**
             * @description Encryption nonce (base64url encoded)
             * @example base64url-encoded-nonce
             */
            nonce: string;
            /**
             * @description Sender device ID
             * @example 01234567-89ab-cdef-0123-456789abcdef
             */
            sender_device_id: string;
            /**
             * @description User ID
             * @example 01234567-89ab-cdef-0123-456789abcdef
             */
            user_id: string;
            /**
             * @description Workspace ID
             * @example 01234567-89ab-cdef-0123-456789abcdef
             */
            workspace_id: string;
        };
        /** @description Workspace response */
        WorkspaceResponse: {
            /** @description Creation timestamp */
            created_at: string;
            /**
             * @description Workspace ID (UUID)
             * @example 01234567-89ab-cdef-0123-456789abcdef
             */
            id: string;
            /**
             * @description Workspace name
             * @example My Workspace
             */
            name: string;
            /**
             * @description Owner user ID
             * @example 01234567-89ab-cdef-0123-456789abcdef
             */
            owner_id: string;
            /**
             * @description Workspace slug
             * @example my-workspace
             */
            slug: string;
            /** @description Last update timestamp */
            updated_at: string;
        };
        /** @description Workspace with membership response */
        WorkspaceWithMembershipResponse: {
            /** @description User's membership in the workspace */
            membership: components["schemas"]["MembershipResponse"];
            /** @description Workspace details */
            workspace: components["schemas"]["WorkspaceResponse"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login successful. Session cookie is set. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthErrorResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthErrorResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logout successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthErrorResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description User registered successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthErrorResponse"];
                };
            };
            /** @description Email already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthErrorResponse"];
                };
            };
        };
    };
    get_salt: {
        parameters: {
            query: {
                /** @description User email address */
                email: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Salt and KDF parameters */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetSaltResponse"];
                };
            };
            /** @description Invalid email */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthErrorResponse"];
                };
            };
        };
    };
    get_document: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Document ID */
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Document details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentErrorResponse"];
                };
            };
            /** @description Permission denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentErrorResponse"];
                };
            };
            /** @description Document not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentErrorResponse"];
                };
            };
        };
    };
    delete_document: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Document ID */
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Document deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Folder not empty */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentErrorResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentErrorResponse"];
                };
            };
            /** @description Permission denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentErrorResponse"];
                };
            };
            /** @description Document not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentErrorResponse"];
                };
            };
        };
    };
    update_document: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Document ID */
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDocumentRequest"];
            };
        };
        responses: {
            /** @description Document updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentErrorResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentErrorResponse"];
                };
            };
            /** @description Permission denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentErrorResponse"];
                };
            };
            /** @description Document not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentErrorResponse"];
                };
            };
        };
    };
    archive_document: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Document ID */
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Document archived */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentErrorResponse"];
                };
            };
            /** @description Permission denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentErrorResponse"];
                };
            };
            /** @description Document not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentErrorResponse"];
                };
            };
            /** @description Already archived */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentErrorResponse"];
                };
            };
        };
    };
    unarchive_document: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Document ID */
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Document unarchived */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Document not archived */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentErrorResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentErrorResponse"];
                };
            };
            /** @description Permission denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentErrorResponse"];
                };
            };
            /** @description Document not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentErrorResponse"];
                };
            };
        };
    };
    get_document_key: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Document ID */
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Key found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentKeyResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncryptionErrorResponse"];
                };
            };
            /** @description Permission denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncryptionErrorResponse"];
                };
            };
            /** @description Key not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncryptionErrorResponse"];
                };
            };
        };
    };
    save_document_key: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Document ID */
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveDocumentKeyRequest"];
            };
        };
        responses: {
            /** @description Key saved successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentKeyResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncryptionErrorResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncryptionErrorResponse"];
                };
            };
            /** @description Permission denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncryptionErrorResponse"];
                };
            };
            /** @description Document not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncryptionErrorResponse"];
                };
            };
        };
    };
    get_workspace_key: {
        parameters: {
            query: {
                /** @description Device ID */
                device_id: string;
            };
            header?: never;
            path: {
                /** @description Workspace ID */
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Key found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceKeyResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncryptionErrorResponse"];
                };
            };
            /** @description Permission denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncryptionErrorResponse"];
                };
            };
            /** @description Key not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncryptionErrorResponse"];
                };
            };
        };
    };
    save_workspace_key: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workspace ID */
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveWorkspaceKeyRequest"];
            };
        };
        responses: {
            /** @description Key saved successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceKeyResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncryptionErrorResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncryptionErrorResponse"];
                };
            };
            /** @description Permission denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncryptionErrorResponse"];
                };
            };
        };
    };
    list_workspaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of user's workspaces */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListWorkspacesResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceErrorResponse"];
                };
            };
        };
    };
    get_workspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workspace ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workspace details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceWithMembershipResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceErrorResponse"];
                };
            };
            /** @description Not a member of this workspace */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceErrorResponse"];
                };
            };
            /** @description Workspace not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceErrorResponse"];
                };
            };
        };
    };
    list_documents: {
        parameters: {
            query: {
                /** @description Filter by parent ID */
                parent_id?: string;
                /** @description Only return root documents */
                root_only: boolean;
                /** @description Include archived documents */
                include_archived: boolean;
            };
            header?: never;
            path: {
                /** @description Workspace ID */
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of documents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListDocumentsResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentErrorResponse"];
                };
            };
            /** @description Not a member of this workspace */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentErrorResponse"];
                };
            };
        };
    };
    create_document: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workspace ID */
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDocumentRequest"];
            };
        };
        responses: {
            /** @description Document created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentErrorResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentErrorResponse"];
                };
            };
            /** @description Permission denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentErrorResponse"];
                };
            };
            /** @description Slug conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentErrorResponse"];
                };
            };
        };
    };
}
