/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login with password authentication
         * @description Authenticates a user with email and authKey.
         *     Session token is set via HttpOnly cookie (not in response body).
         *     Client should derive authKey from password using Argon2id + HKDF.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout and clear session
         * @description Clears the session cookie. Client should also clear DSK from IndexedDB.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user info and encrypted keys
         * @description Returns user info and encrypted keys for session restoration.
         *     Requires valid session cookie. Used when client has DSK cached but needs encrypted keys.
         */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new password user
         * @description Creates a new user account with password authentication and E2EE keys.
         *     All encryption is performed client-side; server stores encrypted data only.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/salt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get salt and KDF parameters for login
         * @description Returns the salt and KDF parameters needed to derive the master key.
         *     For unknown users, returns a deterministic dummy salt to prevent user enumeration.
         *     KDF parameters are always the global default settings.
         */
        get: operations["get_salt"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Error response */
        AuthErrorResponse: {
            /**
             * @description Error message
             * @example invalid email
             */
            error: string;
        };
        /** @description Get salt query parameters (HTTP) */
        GetSaltQueryParams: {
            /**
             * @description User email address
             * @example user@example.com
             */
            email: string;
        };
        /** @description Get salt response */
        GetSaltResponse: {
            /** @description KDF parameters */
            kdf_params: components["schemas"]["KdfParamsResponse"];
            /**
             * @description KDF type (always "argon2id")
             * @example argon2id
             */
            kdf_type: string;
            /**
             * @description Salt for KDF (base64 encoded, 32 bytes)
             * @example base64-encoded-salt
             */
            salt: string;
        };
        /** @description KDF parameters response */
        KdfParamsResponse: {
            /**
             * Format: int32
             * @description Memory cost in KiB
             * @example 65536
             */
            memory_cost: number;
            /**
             * Format: int32
             * @description Parallelism factor
             * @example 4
             */
            parallelism: number;
            /**
             * Format: int32
             * @description Time cost (iterations)
             * @example 3
             */
            time_cost: number;
        };
        /** @description Login request */
        LoginRequest: {
            /**
             * @description authKey for authentication (base64url encoded)
             * @example base64url-encoded-auth-key
             */
            auth_key: string;
            /**
             * @description User email address
             * @example user@example.com
             */
            email: string;
            /**
             * @description Remember me flag for extended session duration
             * @example false
             */
            remember_me: boolean;
        };
        /**
         * @description Login response
         *
         *     Session token is set via HttpOnly cookie, not in JSON body.
         */
        LoginResponse: {
            /**
             * @description User email
             * @example user@example.com
             */
            email: string;
            /**
             * @description Encrypted ECDH private key (base64url encoded)
             * @example base64url-encoded-encrypted-ecdh-private
             */
            encrypted_ecdh_private: string;
            /**
             * @description Encrypted ECDH private key nonce (base64url encoded)
             * @example base64url-encoded-nonce
             */
            encrypted_ecdh_private_nonce: string;
            /**
             * @description Encrypted signing private key (base64url encoded)
             * @example base64url-encoded-encrypted-signing-private
             */
            encrypted_signing_private: string;
            /**
             * @description Encrypted signing private key nonce (base64url encoded)
             * @example base64url-encoded-nonce
             */
            encrypted_signing_private_nonce: string;
            /**
             * @description Encrypted UMK (base64url encoded)
             * @example base64url-encoded-encrypted-umk
             */
            encrypted_umk: string;
            /** @description Session expiration timestamp */
            expires_at: string;
            /**
             * @description UMK nonce (base64url encoded)
             * @example base64url-encoded-nonce
             */
            umk_nonce: string;
            /**
             * @description User ID
             * @example 01234567-89ab-cdef-0123-456789abcdef
             */
            user_id: string;
        };
        /** @description Logout response */
        LogoutResponse: {
            /**
             * @description Success message
             * @example logged out
             */
            message: string;
        };
        /** @description Current user response (for session restoration) */
        MeResponse: {
            /**
             * @description Authentication type ("password" or "oauth")
             * @example password
             */
            auth_type: string;
            /**
             * @description User email
             * @example user@example.com
             */
            email: string;
            /**
             * @description Encrypted ECDH private key (base64url encoded)
             * @example base64url-encoded-encrypted-ecdh-private
             */
            encrypted_ecdh_private: string;
            /**
             * @description Encrypted ECDH private key nonce (base64url encoded)
             * @example base64url-encoded-nonce
             */
            encrypted_ecdh_private_nonce: string;
            /**
             * @description Encrypted signing private key (base64url encoded)
             * @example base64url-encoded-encrypted-signing-private
             */
            encrypted_signing_private: string;
            /**
             * @description Encrypted signing private key nonce (base64url encoded)
             * @example base64url-encoded-nonce
             */
            encrypted_signing_private_nonce: string;
            /**
             * @description Encrypted UMK (base64url encoded, null for OAuth users)
             * @example base64url-encoded-encrypted-umk
             */
            encrypted_umk?: string | null;
            /** @description Session expiration timestamp */
            expires_at: string;
            /**
             * @description User display name
             * @example John Doe
             */
            name: string;
            /**
             * @description UMK nonce (base64url encoded, null for OAuth users)
             * @example base64url-encoded-nonce
             */
            umk_nonce?: string | null;
            /**
             * @description User ID
             * @example 01234567-89ab-cdef-0123-456789abcdef
             */
            user_id: string;
        };
        /** @description Register password user request */
        RegisterRequest: {
            /**
             * @description authKey for login (base64url encoded)
             * @example base64url-encoded-auth-key
             */
            auth_key: string;
            /**
             * @description ECDH public key (base64url encoded, 32 bytes)
             * @example base64url-encoded-ecdh-public-key
             */
            ecdh_public_key: string;
            /**
             * @description User email address
             * @example user@example.com
             */
            email: string;
            /**
             * @description Encrypted ECDH private key (base64url encoded)
             * @example base64url-encoded-encrypted-ecdh-private
             */
            encrypted_ecdh_private: string;
            /**
             * @description Encrypted ECDH private key nonce (base64url encoded)
             * @example base64url-encoded-nonce
             */
            encrypted_ecdh_private_nonce: string;
            /**
             * @description Encrypted signing private key (base64url encoded)
             * @example base64url-encoded-encrypted-signing-private
             */
            encrypted_signing_private: string;
            /**
             * @description Encrypted signing private key nonce (base64url encoded)
             * @example base64url-encoded-nonce
             */
            encrypted_signing_private_nonce: string;
            /**
             * @description Encrypted UMK (base64url encoded)
             * @example base64url-encoded-encrypted-umk
             */
            encrypted_umk: string;
            /**
             * @description User display name
             * @example John Doe
             */
            name: string;
            /**
             * @description Recovery encrypted UMK (base64url encoded)
             * @example base64url-encoded-recovery-encrypted-umk
             */
            recovery_encrypted_umk: string;
            /**
             * @description Recovery nonce (base64url encoded)
             * @example base64url-encoded-recovery-nonce
             */
            recovery_nonce: string;
            /**
             * @description Salt for KDF (base64url encoded, 32 bytes)
             * @example base64url-encoded-salt
             */
            salt: string;
            /**
             * @description Signing public key (base64url encoded, 32 bytes)
             * @example base64url-encoded-signing-public-key
             */
            signing_public_key: string;
            /**
             * @description UMK nonce (base64url encoded)
             * @example base64url-encoded-nonce
             */
            umk_nonce: string;
        };
        /** @description Register response */
        RegisterResponse: {
            /**
             * @description User email address
             * @example user@example.com
             */
            email: string;
            /**
             * @description User ID (UUID)
             * @example 01234567-89ab-cdef-0123-456789abcdef
             */
            id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login successful. Session cookie is set. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthErrorResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthErrorResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logout successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthErrorResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description User registered successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthErrorResponse"];
                };
            };
            /** @description Email already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthErrorResponse"];
                };
            };
        };
    };
    get_salt: {
        parameters: {
            query: {
                /** @description User email address */
                email: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Salt and KDF parameters */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetSaltResponse"];
                };
            };
            /** @description Invalid email */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthErrorResponse"];
                };
            };
        };
    };
}
