import {
  handleClearTransientKeys,
  handleGetDeviceId,
  handleGetPublicKeys,
  handleHasStoredDeviceKeys,
  handleHasStoredDsk,
  handleDeleteAuthBootstrapWithDsk,
  handleDeleteWrappedUmkWithDsk,
  handleLoadAuthBootstrap,
  handleInit,
  handleInitFromPassword,
  handleImportIdentityKeysFromKeyRestore,
  handleIsReady,
  handleLoadStoredDsk,
  handleLock,
  handleSetInitialized,
  handleSetUserContext,
  handleStoreAuthBootstrap,
} from "../lifecycle";
import type { RequestHandlerTable } from "./shared";

export const lifecycleRequestHandlers = {
  "clear-transient-keys": () => handleClearTransientKeys(),
  "get-device-id": (state) => handleGetDeviceId(state),
  "get-public-keys": (state) => handleGetPublicKeys(state),
  "has-stored-device-keys": () => handleHasStoredDeviceKeys(),
  "has-stored-dsk": () => handleHasStoredDsk(),
  "delete-auth-bootstrap-with-dsk": () => handleDeleteAuthBootstrapWithDsk(),
  "delete-wrapped-umk-with-dsk": () => handleDeleteWrappedUmkWithDsk(),
  init: (state, payload) => handleInit(state, payload),
  "init-from-password": (state, payload) => handleInitFromPassword(state, payload),
  "import-identity-keys-from-key-restore": (state, payload) =>
    handleImportIdentityKeysFromKeyRestore(state, payload),
  "is-ready": (state) => handleIsReady(state),
  "load-auth-bootstrap": (state) => handleLoadAuthBootstrap(state),
  "load-stored-dsk": (state) => handleLoadStoredDsk(state),
  lock: (state) => handleLock(state),
  "set-initialized": (state) => handleSetInitialized(state),
  "set-user-context": (state, payload) => handleSetUserContext(state, payload),
  "store-auth-bootstrap": (state, payload) => handleStoreAuthBootstrap(state, payload),
} satisfies RequestHandlerTable;
