/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthRecoveryRouteImport } from './routes/auth/recovery'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthDeviceRegisterRouteImport } from './routes/auth/device-register'
import { Route as AuthenticatedWorkspaceIndexRouteImport } from './routes/_authenticated/workspace/index'
import { Route as AuthenticatedWorkspaceWorkspaceIdRouteImport } from './routes/_authenticated/workspace/$workspaceId'
import { Route as AuthenticatedDocumentDocumentIdRouteImport } from './routes/_authenticated/document/$documentId'

const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRecoveryRoute = AuthRecoveryRouteImport.update({
  id: '/auth/recovery',
  path: '/auth/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDeviceRegisterRoute = AuthDeviceRegisterRouteImport.update({
  id: '/auth/device-register',
  path: '/auth/device-register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspaceIndexRoute =
  AuthenticatedWorkspaceIndexRouteImport.update({
    id: '/workspace/',
    path: '/workspace/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspaceWorkspaceIdRoute =
  AuthenticatedWorkspaceWorkspaceIdRouteImport.update({
    id: '/workspace/$workspaceId',
    path: '/workspace/$workspaceId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDocumentDocumentIdRoute =
  AuthenticatedDocumentDocumentIdRouteImport.update({
    id: '/document/$documentId',
    path: '/document/$documentId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/invite': typeof InviteRoute
  '/auth/device-register': typeof AuthDeviceRegisterRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/recovery': typeof AuthRecoveryRoute
  '/auth/register': typeof AuthRegisterRoute
  '/document/$documentId': typeof AuthenticatedDocumentDocumentIdRoute
  '/workspace/$workspaceId': typeof AuthenticatedWorkspaceWorkspaceIdRoute
  '/workspace/': typeof AuthenticatedWorkspaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invite': typeof InviteRoute
  '/auth/device-register': typeof AuthDeviceRegisterRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/recovery': typeof AuthRecoveryRoute
  '/auth/register': typeof AuthRegisterRoute
  '/document/$documentId': typeof AuthenticatedDocumentDocumentIdRoute
  '/workspace/$workspaceId': typeof AuthenticatedWorkspaceWorkspaceIdRoute
  '/workspace': typeof AuthenticatedWorkspaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/invite': typeof InviteRoute
  '/auth/device-register': typeof AuthDeviceRegisterRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/recovery': typeof AuthRecoveryRoute
  '/auth/register': typeof AuthRegisterRoute
  '/_authenticated/document/$documentId': typeof AuthenticatedDocumentDocumentIdRoute
  '/_authenticated/workspace/$workspaceId': typeof AuthenticatedWorkspaceWorkspaceIdRoute
  '/_authenticated/workspace/': typeof AuthenticatedWorkspaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/invite'
    | '/auth/device-register'
    | '/auth/login'
    | '/auth/recovery'
    | '/auth/register'
    | '/document/$documentId'
    | '/workspace/$workspaceId'
    | '/workspace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invite'
    | '/auth/device-register'
    | '/auth/login'
    | '/auth/recovery'
    | '/auth/register'
    | '/document/$documentId'
    | '/workspace/$workspaceId'
    | '/workspace'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/invite'
    | '/auth/device-register'
    | '/auth/login'
    | '/auth/recovery'
    | '/auth/register'
    | '/_authenticated/document/$documentId'
    | '/_authenticated/workspace/$workspaceId'
    | '/_authenticated/workspace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  InviteRoute: typeof InviteRoute
  AuthDeviceRegisterRoute: typeof AuthDeviceRegisterRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRecoveryRoute: typeof AuthRecoveryRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/recovery': {
      id: '/auth/recovery'
      path: '/auth/recovery'
      fullPath: '/auth/recovery'
      preLoaderRoute: typeof AuthRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/device-register': {
      id: '/auth/device-register'
      path: '/auth/device-register'
      fullPath: '/auth/device-register'
      preLoaderRoute: typeof AuthDeviceRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspace/': {
      id: '/_authenticated/workspace/'
      path: '/workspace'
      fullPath: '/workspace/'
      preLoaderRoute: typeof AuthenticatedWorkspaceIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspace/$workspaceId': {
      id: '/_authenticated/workspace/$workspaceId'
      path: '/workspace/$workspaceId'
      fullPath: '/workspace/$workspaceId'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkspaceIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/document/$documentId': {
      id: '/_authenticated/document/$documentId'
      path: '/document/$documentId'
      fullPath: '/document/$documentId'
      preLoaderRoute: typeof AuthenticatedDocumentDocumentIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDocumentDocumentIdRoute: typeof AuthenticatedDocumentDocumentIdRoute
  AuthenticatedWorkspaceWorkspaceIdRoute: typeof AuthenticatedWorkspaceWorkspaceIdRoute
  AuthenticatedWorkspaceIndexRoute: typeof AuthenticatedWorkspaceIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDocumentDocumentIdRoute: AuthenticatedDocumentDocumentIdRoute,
  AuthenticatedWorkspaceWorkspaceIdRoute:
    AuthenticatedWorkspaceWorkspaceIdRoute,
  AuthenticatedWorkspaceIndexRoute: AuthenticatedWorkspaceIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  InviteRoute: InviteRoute,
  AuthDeviceRegisterRoute: AuthDeviceRegisterRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRecoveryRoute: AuthRecoveryRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
