export const COMMON_TRANSCRIPT_KEYS = [
  "label",
  "owner_id",
  "owner_kind",
  "protocol",
  "signature_suite_id",
  "signature_suite_rank",
  "signing_purpose",
  "surface_id",
  "surface_variant",
  "transcript_owner",
  "version",
] as const;

export const OWNER_EXACT_PAYLOAD_KEYS: Record<string, readonly string[]> = {
  "pq_wrap:none": [
    "actor",
    "authority_boundary",
    "subject_hashes",
    "subject_protocol",
    "subject_suite_id",
    "subject_suite_rank",
    "subject_version",
  ],
  "key_directory_checkpoint:device_authorized": [
    "authority_boundary",
    "scope",
    "signer",
    "suite_policy",
    "subject_hash",
    "subject_protocol",
    "subject_version",
  ],
  "key_directory_checkpoint:identity_initial": [
    "authority_boundary",
    "scope",
    "signer",
    "suite_policy",
    "subject_hash",
    "subject_protocol",
    "subject_version",
  ],
  "key_directory_checkpoint:identity_active": [
    "authority_boundary",
    "scope",
    "signer",
    "suite_policy",
    "subject_hash",
    "subject_protocol",
    "subject_version",
  ],
  "key_directory_checkpoint:identity_rotation": [
    "authority_boundary",
    "scope",
    "signer",
    "suite_policy",
    "subject_hash",
    "subject_protocol",
    "subject_version",
  ],
  "key_directory_checkpoint:workspace_initial": [
    "authority_boundary",
    "scope",
    "signer",
    "suite_policy",
    "subject_hash",
    "subject_protocol",
    "subject_version",
  ],
  "key_directory_checkpoint:workspace_authorized": [
    "authority_boundary",
    "scope",
    "signer",
    "suite_policy",
    "subject_hash",
    "subject_protocol",
    "subject_version",
  ],
  "key_directory_checkpoint:invitation_redeem_authority": [
    "authority_boundary",
    "scope",
    "signer",
    "suite_policy",
    "subject_hash",
    "subject_protocol",
    "subject_version",
  ],
  "key_directory_checkpoint:share_participant_document_operation": [
    "authority_boundary",
    "scope",
    "signer",
    "suite_policy",
    "subject_hash",
    "subject_protocol",
    "subject_version",
  ],
  "workspace_pin_bootstrap:none": [
    "actor",
    "authority_boundary",
    "suite_policy",
    "subject_hash",
    "subject_protocol",
    "subject_version",
  ],
  "device_approval:none": [
    "approval_signature_surface",
    "approved_device_registration_sas_hash",
    "approving_device_key_directory_proof_hash",
    "approving_key_checkpoint_hash",
    "approving_key_checkpoint_sequence",
    "approving_owner_id",
    "approving_owner_kind",
    "approving_signing_key_id",
    "device_approval_kek_initial_delivery_commitments",
    "pending_registration_challenge_hash",
    "pending_registration_id",
    "target_device_client_nonce_hash",
    "target_device_encryption_key_id",
    "target_device_hybrid_encryption_public_key_material_hash",
    "target_device_hybrid_signing_public_key_material_hash",
    "target_device_id",
    "target_device_signing_key_id",
    "target_key_checkpoint_hash",
    "target_key_checkpoint_sequence",
    "trust_transfer_delivery_commitment",
    "umk_distribution_delivery_commitment",
  ],
  "device_revocation:none": [
    "actor",
    "authority_boundary",
    "revocation",
    "subject_hash",
    "subject_protocol",
    "subject_version",
  ],
  "device_key_deletion_proof:device_key_deletion_proof": [
    "actor",
    "authority_boundary",
    "subject_hash",
    "subject_protocol",
    "subject_version",
  ],
  "device_key_deletion_proof:identity_key_deletion_proof": [
    "actor",
    "authority_boundary",
    "subject_hash",
    "subject_protocol",
    "subject_version",
  ],
  "document_snapshot:share_participant_device": [
    "actor",
    "authority_boundary",
    "ciphertext_hash",
    "document_id",
    "nonce",
    "public_data",
    "snapshot_id",
    "subject_hash",
    "subject_protocol",
    "subject_version",
  ],
  "document_snapshot:workspace_device": [
    "actor",
    "authority_boundary",
    "ciphertext_hash",
    "document_id",
    "nonce",
    "public_data",
    "snapshot_id",
    "subject_hash",
    "subject_protocol",
    "subject_version",
  ],
  "document_update:share_participant_device": [
    "actor",
    "authority_boundary",
    "ciphertext_hash",
    "document_id",
    "nonce",
    "public_data",
    "subject_hash",
    "subject_protocol",
    "subject_version",
  ],
  "document_update:workspace_device": [
    "actor",
    "authority_boundary",
    "ciphertext_hash",
    "document_id",
    "nonce",
    "public_data",
    "subject_hash",
    "subject_protocol",
    "subject_version",
  ],
  "editor_ephemeral:share_participant_device": [
    "actor",
    "authority_boundary",
    "session",
    "subject_hash",
    "subject_protocol",
    "subject_version",
  ],
  "editor_ephemeral:workspace_device": [
    "actor",
    "authority_boundary",
    "session",
    "subject_hash",
    "subject_protocol",
    "subject_version",
  ],
  "editor_ephemeral_session:share_participant_device": [
    "actor",
    "authority_boundary",
    "session",
    "subject_hash",
    "subject_protocol",
    "subject_version",
  ],
  "editor_ephemeral_session:workspace_device": [
    "actor",
    "authority_boundary",
    "session",
    "subject_hash",
    "subject_protocol",
    "subject_version",
  ],
  "genesis_device_bootstrap:none": [
    "bootstrap_authority",
    "client_nonce",
    "device_encryption_key_id",
    "device_hybrid_encryption_public_key_material_hash",
    "device_id",
    "device_signing_key_id",
    "identity_signing_key_id",
    "subject_protocol",
    "subject_version",
    "user_id",
  ],
  "pop_request:channel_share_participant_device": [
    "actor",
    "challenge",
    "pop_variant",
    "resource",
    "session",
    "transport",
  ],
  "pop_request:channel_user_device": [
    "actor",
    "challenge",
    "pop_variant",
    "resource",
    "session",
    "transport",
  ],
  "pop_request:http_share_participant_device": [
    "actor",
    "challenge",
    "pop_variant",
    "request",
    "session",
    "transport",
  ],
  "pop_request:http_user_device": [
    "actor",
    "challenge",
    "pop_variant",
    "request",
    "session",
    "transport",
  ],
  "recovery_device_approval:none": [
    "approval_signature_surface",
    "approving_key_checkpoint_hash",
    "approving_key_checkpoint_sequence",
    "approving_owner_id",
    "approving_owner_kind",
    "approving_signing_key_id",
    "pending_registration_binding_hash",
    "pending_registration_challenge_hash",
    "pending_registration_id",
    "recovery_capability_hash",
    "recovery_session_transcript_hash",
    "target_device_client_nonce_hash",
    "target_device_encryption_key_id",
    "target_device_hybrid_encryption_public_key_material_hash",
    "target_device_hybrid_signing_public_key_material_hash",
    "target_device_id",
    "target_device_signing_key_id",
    "target_key_checkpoint_hash",
    "target_key_checkpoint_sequence",
  ],
  "recovery_session:none": [
    "candidate_user_checkpoint_hash",
    "candidate_user_checkpoint_sequence",
    "candidate_user_event_head_hash",
    "candidate_user_event_head_sequence",
    "owner_user_id",
    "pending_registration_binding_hash",
    "pending_registration_id",
    "recipient_device_id",
    "recovered_identity_signing_key_id",
    "recovery_authorization_key_id",
    "recovery_capability_hash",
    "recovery_session_id",
    "server_challenge_hash",
    "subject_protocol",
    "subject_version",
  ],
  "recovery_authorization_proof:none": [
    "pending_registration_binding_hash",
    "recipient_device_id",
    "recovery_authorization_key_id",
    "server_challenge_hash",
    "subject_protocol",
    "subject_version",
  ],
  "pin_gossip_statement:none": [
    "pin_gossip",
    "subject_hash",
    "subject_protocol",
    "subject_version",
  ],
  "recipient_bound_authorization:none": [
    "actor",
    "authority_boundary",
    "freshness",
    "recipient",
    "subject_hash",
    "subject_protocol",
    "subject_version",
  ],
  "share_capability_authorization:none": [
    "authorization",
    "share_state",
    "subject_hash",
    "subject_protocol",
    "subject_version",
  ],
  "share_participant_device_authorization:none": [
    "capability_context_hash",
    "latest_bootstrap_event_hash",
    "participant_encryption_key_id",
    "participant_signing_key_id",
    "permission",
    "scope_id",
    "scope_kind",
    "share_created_event_hash",
    "share_id",
    "share_participant_device_id",
    "share_participant_principal_id",
    "share_session_id",
  ],
  "responder_prekey:none": [
    "freshness",
    "responder",
    "subject_hash",
    "subject_protocol",
    "subject_version",
  ],
  "initiator_ake_commitment:none": [
    "ake_inputs",
    "binding",
    "initiator",
    "subject_hash",
    "subject_protocol",
    "subject_version",
    "suite",
  ],
  "initial_key_delivery:umk_distribution": [
    "ake",
    "authority",
    "delivery",
    "recipient",
    "sender",
    "subject_hash",
    "subject_protocol",
    "subject_version",
    "suite",
  ],
  "initial_key_delivery:device_approval_kek_initial": [
    "ake",
    "authority",
    "delivery",
    "recipient",
    "sender",
    "subject_hash",
    "subject_protocol",
    "subject_version",
    "suite",
  ],
  "initial_key_delivery:trust_transfer": [
    "ake",
    "authority",
    "delivery",
    "recipient",
    "sender",
    "subject_hash",
    "subject_protocol",
    "subject_version",
    "suite",
  ],
};

export const KEY_DIRECTORY_EVENT_VARIANTS = [
  "device_key_added",
  "encryption_key_revoked",
  "identity_key_added",
  "member_added",
  "member_removed",
  "document_snapshot_accepted",
  "document_update_accepted",
  "old_key_deleted",
  "rotation_completed",
  "rotation_started",
  "share_created",
  "share_exclusion_changed",
  "share_key_scope_added",
  "share_key_scope_replaced",
  "share_key_scope_removed",
  "share_metadata_updated",
  "recipient_bound_delivery_admitted",
  "share_revoked",
  "signing_key_revoked",
  "suite_policy_changed",
  "workspace_invitation_created",
  "workspace_invitation_bootstrap_updated",
  "workspace_invitation_revoked",
  "workspace_invitation_redeemed",
  "guest_invitation_created",
  "guest_invitation_bootstrap_updated",
  "guest_invitation_revoked",
  "guest_invitation_redeemed",
  "guest_grant_revoked",
  "guest_device_revoked",
  "wrap_issued",
] as const;

export const NESTED_OWNER_EXACT_KEYS: Record<string, Record<string, readonly string[]>> = {
  "pq_wrap:none": {
    actor: [
      "device_id",
      "key_checkpoint_hash",
      "key_checkpoint_sequence",
      "key_scope_id",
      "key_scope_kind",
      "signer_kind",
      "signing_key_id",
      "user_id",
    ],
    authority_boundary: [
      "covered_event_head_hash",
      "covered_event_head_sequence",
      "event_hash",
      "operation_checkpoint_hash",
      "operation_checkpoint_sequence",
      "scope_id",
      "scope_kind",
    ],
    subject_hashes: [
      "aad_hash",
      "hpke_info_hash",
      "resource_hash",
      "wrap_body_hash",
      "wrap_event_body_hash",
      "wrap_event_hash",
    ],
  },
  "genesis_device_bootstrap:none": {
    bootstrap_authority: [
      "authority_kind",
      "registration_challenge_hash",
      "user_identity_public_key_hash",
    ],
  },
  "pop_request:*": {
    session: ["is_recovery", "session_id_hash", "session_kind"],
  },
  "pop_request:channel_share_participant_device": {
    actor: [
      "key_checkpoint_hash",
      "key_checkpoint_sequence",
      "key_scope_id",
      "key_scope_kind",
      "share_id",
      "share_participant_device_id",
      "share_participant_principal_id",
      "signer_kind",
      "signing_key_id",
    ],
    resource: [
      "channel_event",
      "document_id",
      "event_name",
      "join_push_kind",
      "payload_hash",
      "scope_kind",
      "share_id",
      "topic",
    ],
    session: ["is_recovery", "session_id_hash", "session_kind", "share_id"],
  },
  "pop_request:channel_user_device": {
    actor: [
      "device_id",
      "key_checkpoint_hash",
      "key_checkpoint_sequence",
      "key_scope_id",
      "key_scope_kind",
      "signer_kind",
      "signing_key_id",
      "user_id",
    ],
    resource: [
      "channel_event",
      "document_id",
      "event_name",
      "join_push_kind",
      "payload_hash",
      "scope_kind",
      "share_id",
      "topic",
    ],
    session: ["is_recovery", "session_id_hash", "session_kind"],
  },
  "pop_request:http_share_participant_device": {
    actor: [
      "key_checkpoint_hash",
      "key_checkpoint_sequence",
      "key_scope_id",
      "key_scope_kind",
      "share_id",
      "share_participant_device_id",
      "share_participant_principal_id",
      "signer_kind",
      "signing_key_id",
    ],
    request: ["body_hash", "canonical_query", "method", "path", "query_hash"],
    session: ["is_recovery", "session_id_hash", "session_kind", "share_id"],
  },
  "pop_request:http_user_device": {
    actor: [
      "device_id",
      "key_checkpoint_hash",
      "key_checkpoint_sequence",
      "key_scope_id",
      "key_scope_kind",
      "signer_kind",
      "signing_key_id",
      "user_id",
    ],
    request: ["body_hash", "canonical_query", "method", "path", "query_hash"],
    session: ["is_recovery", "session_id_hash", "session_kind"],
  },
  "key_directory_checkpoint:*": {
    scope: [
      "covered_event_head_hash",
      "covered_event_head_sequence",
      "checkpoint_sequence",
      "previous_checkpoint_hash",
      "scope_id",
      "scope_kind",
    ],
    signer: [],
    authority_boundary: [
      "authorizing_checkpoint_hash",
      "authorizing_checkpoint_sequence",
      "required_authority",
    ],
    suite_policy: ["allowed_suite_ids_hash", "min_suite_rank", "suite_policy_version"],
  },
  "key_directory_event:*": {
    event: [
      "event_body_hash",
      "event_type",
      "previous_event_hash",
      "scope_id",
      "scope_kind",
      "sequence",
    ],
    actor: [],
    authority_boundary: [
      "checkpoint_hash",
      "checkpoint_sequence",
      "required_authority",
      "scope_id",
      "scope_kind",
    ],
  },
  "workspace_pin_bootstrap:none": {
    actor: [
      "device_id",
      "key_checkpoint_hash",
      "key_checkpoint_sequence",
      "key_scope_id",
      "key_scope_kind",
      "signer_kind",
      "signing_key_id",
      "user_id",
    ],
    authority_boundary: [
      "checkpoint_hash",
      "checkpoint_sequence",
      "event_head_hash",
      "event_head_sequence",
      "issuing_event_hash",
      "scope_id",
      "scope_kind",
    ],
    suite_policy: ["allowed_suite_ids_hash", "min_suite_rank", "suite_policy_version"],
  },
  "recipient_bound_authorization:none": {
    actor: [
      "device_id",
      "key_checkpoint_hash",
      "key_checkpoint_sequence",
      "key_scope_id",
      "key_scope_kind",
      "signer_kind",
      "signing_key_id",
      "user_id",
    ],
    authority_boundary: [
      "authorization_id",
      "context_id",
      "context_kind",
      "current_checkpoint_hash",
      "current_checkpoint_sequence",
      "current_event_head_hash",
      "current_event_head_sequence",
      "redeem_attempt_id",
      "resource_hash",
      "workspace_id",
      "workspace_pin_bootstrap_hash",
    ],
    recipient: [
      "encryption_key_id",
      "recipient_device_id",
      "recipient_kind",
      "recipient_principal_id",
    ],
    freshness: [
      "live_redeem_challenge_hash",
      "not_after_event_sequence",
      "recipient_nonce_state_hash",
      "recipient_redeem_nonce",
      "redeem_freshness_proof_hash",
    ],
  },
  "share_capability_authorization:none": {
    authorization: ["token_hash", "workspace_pin_bootstrap_hash"],
    share_state: [
      "capability_context_hash",
      "created_event_hash",
      "latest_bootstrap_event_hash",
      "password_capability_secret_commitment",
      "password_protected",
      "permission",
      "scope_id",
      "scope_kind",
      "share_capability_secret_commitment",
      "share_id",
    ],
  },
  "pin_gossip_statement:none": {
    pin_gossip: ["statement_hash", "statement"],
  },
  "document_update:*": {
    actor: [
      "device_id",
      "key_checkpoint_hash",
      "key_checkpoint_sequence",
      "key_scope_id",
      "key_scope_kind",
      "signer_kind",
      "signing_key_id",
      "user_id",
    ],
    authority_boundary: [
      "admission_event_type",
      "admission_nonce",
      "document_permission_proof_hash",
      "min_dek_version",
      "previous_workspace_event_hash",
      "previous_workspace_event_sequence",
    ],
    public_data: [
      "authorityContextKey",
      "authorityId",
      "authorityKind",
      "authorityPermissionVersion",
      "authorityScopeId",
      "clock",
      "docId",
      "keyCheckpointHash",
      "keyCheckpointSequence",
      "keyVersion",
      "ownerId",
      "ownerKind",
      "refSnapshotId",
      "signingKeyId",
      "timestamp",
      "updateHash",
    ],
  },
  "document_update:share_participant_device": {
    actor: [
      "key_checkpoint_hash",
      "key_checkpoint_sequence",
      "key_scope_id",
      "key_scope_kind",
      "share_id",
      "share_participant_device_id",
      "share_participant_principal_id",
      "signer_kind",
      "signing_key_id",
    ],
    authority_boundary: [
      "admission_event_type",
      "admission_nonce",
      "document_permission_proof_hash",
      "min_dek_version",
      "previous_workspace_event_hash",
      "previous_workspace_event_sequence",
    ],
    public_data: [
      "authorityContextKey",
      "authorityId",
      "authorityKind",
      "authorityPermissionVersion",
      "authorityScopeId",
      "clock",
      "docId",
      "keyCheckpointHash",
      "keyCheckpointSequence",
      "keyVersion",
      "ownerId",
      "ownerKind",
      "refSnapshotId",
      "signingKeyId",
      "timestamp",
      "updateHash",
    ],
  },
  "document_snapshot:*": {
    actor: [
      "device_id",
      "key_checkpoint_hash",
      "key_checkpoint_sequence",
      "key_scope_id",
      "key_scope_kind",
      "signer_kind",
      "signing_key_id",
      "user_id",
    ],
    authority_boundary: [
      "admission_event_type",
      "admission_nonce",
      "document_permission_proof_hash",
      "min_dek_version",
      "previous_workspace_event_hash",
      "previous_workspace_event_sequence",
    ],
    public_data: [
      "authorityContextKey",
      "authorityId",
      "authorityKind",
      "authorityPermissionVersion",
      "authorityScopeId",
      "docId",
      "keyCheckpointHash",
      "keyCheckpointSequence",
      "keyVersion",
      "ownerId",
      "ownerKind",
      "parentProofHash",
      "parentSnapshotId",
      "parentSnapshotUpdateClocks",
      "signingKeyId",
      "snapshotId",
    ],
  },
  "document_snapshot:share_participant_device": {
    actor: [
      "key_checkpoint_hash",
      "key_checkpoint_sequence",
      "key_scope_id",
      "key_scope_kind",
      "share_id",
      "share_participant_device_id",
      "share_participant_principal_id",
      "signer_kind",
      "signing_key_id",
    ],
    authority_boundary: [
      "admission_event_type",
      "admission_nonce",
      "document_permission_proof_hash",
      "min_dek_version",
      "previous_workspace_event_hash",
      "previous_workspace_event_sequence",
    ],
    public_data: [
      "authorityContextKey",
      "authorityId",
      "authorityKind",
      "authorityPermissionVersion",
      "authorityScopeId",
      "docId",
      "keyCheckpointHash",
      "keyCheckpointSequence",
      "keyVersion",
      "ownerId",
      "ownerKind",
      "parentProofHash",
      "parentSnapshotId",
      "parentSnapshotUpdateClocks",
      "signingKeyId",
      "snapshotId",
    ],
  },
  "editor_ephemeral:*": {
    actor: [
      "device_id",
      "key_checkpoint_hash",
      "key_checkpoint_sequence",
      "key_scope_id",
      "key_scope_kind",
      "signer_kind",
      "signing_key_id",
      "user_id",
    ],
    authority_boundary: [
      "actor_active_proof_hash",
      "document_permission_proof_hash",
      "expires_event_sequence",
      "workspace_event_head_hash",
      "workspace_event_head_sequence",
    ],
    session: ["channel_id", "document_id", "message_nonce", "workspace_id"],
  },
  "editor_ephemeral:share_participant_device": {
    actor: [
      "key_checkpoint_hash",
      "key_checkpoint_sequence",
      "key_scope_id",
      "key_scope_kind",
      "share_id",
      "share_participant_device_id",
      "share_participant_principal_id",
      "signer_kind",
      "signing_key_id",
    ],
    authority_boundary: [
      "actor_active_proof_hash",
      "document_permission_proof_hash",
      "expires_event_sequence",
      "workspace_event_head_hash",
      "workspace_event_head_sequence",
    ],
    session: ["channel_id", "document_id", "message_nonce", "workspace_id"],
  },
  "editor_ephemeral_session:*": {
    actor: [
      "device_id",
      "key_checkpoint_hash",
      "key_checkpoint_sequence",
      "key_scope_id",
      "key_scope_kind",
      "signer_kind",
      "signing_key_id",
      "user_id",
    ],
    authority_boundary: [
      "actor_active_proof_hash",
      "document_permission_proof_hash",
      "workspace_event_head_hash",
      "workspace_event_head_sequence",
    ],
    session: [
      "channel_id",
      "counter",
      "document_id",
      "expires_event_sequence",
      "proof_direction",
      "proof_type",
      "session_id",
      "session_nonce",
      "workspace_id",
    ],
  },
  "editor_ephemeral_session:share_participant_device": {
    actor: [
      "key_checkpoint_hash",
      "key_checkpoint_sequence",
      "key_scope_id",
      "key_scope_kind",
      "share_participant_device_id",
      "share_participant_principal_id",
      "signer_kind",
      "signing_key_id",
    ],
    authority_boundary: [
      "actor_active_proof_hash",
      "document_permission_proof_hash",
      "workspace_event_head_hash",
      "workspace_event_head_sequence",
    ],
    session: [
      "channel_id",
      "counter",
      "document_id",
      "expires_event_sequence",
      "proof_direction",
      "proof_type",
      "session_id",
      "session_nonce",
      "workspace_id",
    ],
  },
  "initial_key_delivery:*": {
    ake: ["ake_transcript_hash", "initiator_commitment_hash", "operation_id", "purpose"],
    authority: ["sender_authority_kind"],
    delivery: ["ciphertext_hash", "context_hash", "delivery_id", "payload_kind"],
    recipient: ["device_id", "encryption_key_id", "user_id"],
    sender: ["device_id", "signing_key_id", "user_id"],
  },
};
