defmodule RefMDWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :refmd

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_refmd_key",
    signing_salt: "nTggeYX9",
    same_site: "Lax"
  ]

  socket "/api/socket", RefMDWeb.UserSocket,
    websocket: [
      connect_info: [:peer_data, :uri],
      check_origin: {RefMDWeb.Channels.SocketAuth, :check_origin, []},
      serializer: [{RefMDWeb.Channels.StrictJSONSerializer, "~> 2.0.0"}]
    ],
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :refmd,
    gzip: not code_reloading?,
    only: RefMDWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :refmd
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    body_reader: {RefMDWeb.Http.BodyReader, :read_body, []},
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug RefMDWeb.Plugs.ClientIP
  plug RefMDWeb.Plugs.CSP
  plug RefMDWeb.Router
end
